/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTO.java.e.vm
 */
package com.incloud.hcp.service.delta;

import com.incloud.hcp.bean.custom.FiltroAprobadorCustom;
import com.incloud.hcp.bean.custom.MensajeSap;
import com.incloud.hcp.bean.custom.MtrAprobadorCustom;
import com.incloud.hcp.bean.custom.ReemplazoAprobadorCustom;
import com.incloud.hcp.service.MtrAprobadorService;

import java.util.List;

/**
 * Simple Interface for MtrAprobador.
 */
public interface MtrAprobadorDeltaService extends MtrAprobadorService {
    List<MtrAprobadorCustom> listaAprobador (FiltroAprobadorCustom input) throws Exception;
    List<MensajeSap> grabarReemplazo (ReemplazoAprobadorCustom input) throws Exception;
}
