/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTO.java.e.vm
 */
package com.incloud.hcp.service.delta;

import com.incloud.hcp.bean.custom.MensajeSap;
import com.incloud.hcp.bean.custom.RangeSap;
import com.incloud.hcp.service.MtrDetraccionService;

import java.util.List;

/**
 * Simple Interface for MtrDetraccion.
 */
public interface MtrDetraccionDeltaService extends MtrDetraccionService {
    List<MensajeSap> actualizarDetraccion (List<RangeSap> lista) throws Exception;
}
