/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.AppProcesoLog;
import com.incloud.hcp.domain.BaseResponseDomain;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;
import java.util.List;

/**
 * Simple Interface for AppProcesoLog.
 */
@Data
@ToString
@EqualsAndHashCode
public class AppProcesoLogResponse extends BaseResponseDomain<AppProcesoLog> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String fechaInicioEjecucionCondicion;
    private String fechaFinEjecucionCondicion;
    private String estadoEjecucionCondicion;
    private String descripcionEstadoEjecucionCondicion;
    private String moduloCondicion;
    private String claseProgramacionCondicion;
    private String metodoProgramacionCondicion;
    private String parametroEntradaCondicion;
    private String resultadoSalidaCondicion;
    private String duracionMsCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Integer> idList;
    private List<Date> fechaInicioEjecucionList;
    private List<Date> fechaFinEjecucionList;
    private List<String> estadoEjecucionList;
    private List<String> descripcionEstadoEjecucionList;
    private List<String> moduloList;
    private List<String> claseProgramacionList;
    private List<String> metodoProgramacionList;
    private List<String> parametroEntradaList;
    private List<String> resultadoSalidaList;
    private List<Integer> duracionMsList;

}
