/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.AppParametria;
import com.incloud.hcp.domain.BaseResponseDomain;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;
import java.util.List;

/**
 * Simple Interface for AppParametria.
 */
@Data
@ToString
@EqualsAndHashCode
public class AppParametriaResponse extends BaseResponseDomain<AppParametria> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String moduloCondicion;
    private String labelCondicion;
    private String descriptionCondicion;
    private String value1Condicion;
    private String value2Condicion;
    private String value3Condicion;
    private String statusCondicion;
    private String createdByCondicion;
    private String createdDateCondicion;
    private String modifiedByCondicion;
    private String modifiedDateCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Integer> idList;
    private List<String> moduloList;
    private List<String> labelList;
    private List<String> descriptionList;
    private List<String> value1List;
    private List<String> value2List;
    private List<String> value3List;
    private List<String> statusList;
    private List<String> createdByList;
    private List<Date> createdDateList;
    private List<String> modifiedByList;
    private List<Date> modifiedDateList;

}
