/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.BaseResponseDomain;
import com.incloud.hcp.domain.MigCertificado;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Simple Interface for MigCertificado.
 */
@Data
@ToString
@EqualsAndHashCode
public class MigCertificadoResponse extends BaseResponseDomain<MigCertificado> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String nroPedidoCondicion;
    private String codigoCertificadoCondicion;
    private String conceptoCondicion;
    private String fechaDesdeCondicion;
    private String fechaHastaCondicion;
    private String montoTotalCondicion;
    private String montoTotalAjustadoCondicion;
    private String hojaServicioCondicion;
    private String userFirmaACondicion;
    private String userFirmaBCondicion;
    private String solicitanteCondicion;
    private String sociedadCondicion;
    private String monedaCondicion;
    private String proveedorCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Integer> idList;
    private List<String> nroPedidoList;
    private List<String> codigoCertificadoList;
    private List<String> conceptoList;
    private List<Date> fechaDesdeList;
    private List<Date> fechaHastaList;
    private List<BigDecimal> montoTotalList;
    private List<BigDecimal> montoTotalAjustadoList;
    private List<String> hojaServicioList;
    private List<String> userFirmaAList;
    private List<String> userFirmaBList;
    private List<String> solicitanteList;
    private List<String> sociedadList;
    private List<String> monedaList;
    private List<String> proveedorList;

}
