/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.BaseResponseDomain;
import com.incloud.hcp.domain.MtrProveedor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.List;

/**
 * Simple Interface for MtrProveedor.
 */
@Data
@ToString
@EqualsAndHashCode
public class MtrProveedorResponse extends BaseResponseDomain<MtrProveedor> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String rucCondicion;
    private String razonSocialCondicion;
    private String direccionCondicion;
    private String emailContactoCondicion;
    private String codigoIdpCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Integer> idList;
    private List<String> rucList;
    private List<String> razonSocialList;
    private List<String> direccionList;
    private List<String> emailContactoList;
    private List<String> codigoIdpList;

}
