/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain._gproveedor.domain;

import com.google.common.base.MoreObjects;
import com.incloud.hcp.domain.Identifiable;
import com.incloud.hcp.domain.IdentifiableHashBuilder;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;


@Entity
@Table(name = "proveedor_validacion_info_detalle")
public class ProveedorValidacionInfoDetalle implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(ProveedorValidacionInfoDetalle.class.getName());

    // Raw attributes
    private Integer id;
    private String nombreCampoBd;
    private String indEsLista;
    private String valorActual;
    private String valorNuevo;
    private String valorListaActual;
    private String valorListaNuevo;

    // Many to one
    private ProveedorValidacionInfo idProveedorPorValidarInfo;

    @Override
    public String entityClassName() {
        return ProveedorValidacionInfoDetalle.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id_proveedor_por_validar_info_detalle", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_proveedor_validacion_info_detalle")
    @Id
    @SequenceGenerator(name = "seq_proveedor_validacion_info_detalle", sequenceName = "seq_proveedor_validacion_info_detalle", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public ProveedorValidacionInfoDetalle id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [nombreCampoBd] ------------------------

    @NotEmpty
    @Size(max = 255)
    @Column(name = "nombre_campo_bd", nullable = false)
    public String getNombreCampoBd() {
        return nombreCampoBd;
    }

    public void setNombreCampoBd(String nombreCampoBd) {
        this.nombreCampoBd = nombreCampoBd;
    }

    public ProveedorValidacionInfoDetalle nombreCampoBd(String nombreCampoBd) {
        setNombreCampoBd(nombreCampoBd);
        return this;
    }
    // -- [indEsLista] ------------------------

    @NotEmpty
    @Size(max = 1)
    @Column(name = "ind_es_lista", nullable = false, length = 1)
    public String getIndEsLista() {
        return indEsLista;
    }

    public void setIndEsLista(String indEsLista) {
        this.indEsLista = indEsLista;
    }

    public ProveedorValidacionInfoDetalle indEsLista(String indEsLista) {
        setIndEsLista(indEsLista);
        return this;
    }
    // -- [valorActual] ------------------------

    @Size(max = 4000)
    @Column(name = "valor_actual", length = 4000)
    public String getValorActual() {
        return valorActual;
    }

    public void setValorActual(String valorActual) {
        this.valorActual = valorActual;
    }

    public ProveedorValidacionInfoDetalle valorActual(String valorActual) {
        setValorActual(valorActual);
        return this;
    }
    // -- [valorNuevo] ------------------------

    @Size(max = 4000)
    @Column(name = "valor_nuevo", length = 4000)
    public String getValorNuevo() {
        return valorNuevo;
    }

    public void setValorNuevo(String valorNuevo) {
        this.valorNuevo = valorNuevo;
    }

    public ProveedorValidacionInfoDetalle valorNuevo(String valorNuevo) {
        setValorNuevo(valorNuevo);
        return this;
    }
    // -- [valorListaActual] ------------------------

    @Size(max = 2147483647)
    @Column(name = "valor_lista_actual", length = 2147483647)
    public String getValorListaActual() {
        return valorListaActual;
    }

    public void setValorListaActual(String valorListaActual) {
        this.valorListaActual = valorListaActual;
    }

    public ProveedorValidacionInfoDetalle valorListaActual(String valorListaActual) {
        setValorListaActual(valorListaActual);
        return this;
    }
    // -- [valorListaNuevo] ------------------------

    @Size(max = 2147483647)
    @Column(name = "valor_lista_nuevo", length = 2147483647)
    public String getValorListaNuevo() {
        return valorListaNuevo;
    }

    public void setValorListaNuevo(String valorListaNuevo) {
        this.valorListaNuevo = valorListaNuevo;
    }

    public ProveedorValidacionInfoDetalle valorListaNuevo(String valorListaNuevo) {
        setValorListaNuevo(valorListaNuevo);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ProveedorValidacionInfoDetalle.idProveedorPorValidarInfo ==> ProveedorValidacionInfo.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "id_proveedor_por_validar_info", nullable = false)
    @ManyToOne
    public ProveedorValidacionInfo getIdProveedorPorValidarInfo() {
        return idProveedorPorValidarInfo;
    }

    /**
     * Set the {@link #idProveedorPorValidarInfo} without adding this ProveedorValidacionInfoDetalle instance on the passed {@link #idProveedorPorValidarInfo}
     */
    public void setIdProveedorPorValidarInfo(ProveedorValidacionInfo idProveedorPorValidarInfo) {
        this.idProveedorPorValidarInfo = idProveedorPorValidarInfo;
    }

    public ProveedorValidacionInfoDetalle idProveedorPorValidarInfo(ProveedorValidacionInfo idProveedorPorValidarInfo) {
        setIdProveedorPorValidarInfo(idProveedorPorValidarInfo);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ProveedorValidacionInfoDetalle withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ProveedorValidacionInfoDetalle && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this ProveedorValidacionInfoDetalle instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("nombreCampoBd", getNombreCampoBd()) //
                .add("indEsLista", getIndEsLista()) //
                .add("valorActual", getValorActual()) //
                .add("valorNuevo", getValorNuevo()) //
                .add("valorListaActual", getValorListaActual()) //
                .add("valorListaNuevo", getValorListaNuevo()) //
                .toString();
    }
}