/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.CerCertificado;
import com.incloud.hcp.domain.CerDocumentoAdjunto;
import com.incloud.hcp.service.delta.CerDocumentoAdjuntoDeltaService;
import com.incloud.hcp.service.impl.CerDocumentoAdjuntoServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * A simple DTO Facility for CerDocumentoAdjunto.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class CerDocumentoAdjuntoDeltaServiceImpl extends CerDocumentoAdjuntoServiceImpl implements CerDocumentoAdjuntoDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "cerCertificado.id"),
                new Sort.Order(Sort.Direction.DESC, "fechaHistorial"),
                new Sort.Order(Sort.Direction.ASC, "archivoNombre")
        );
        return sort;
    }

    protected Sort setFind(CerDocumentoAdjunto req, ExampleMatcher matcher, Example<CerDocumentoAdjunto> example, Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "cerCertificado.id"),
                new Sort.Order(Sort.Direction.ASC, "tipoAdjunto"),
                new Sort.Order(Sort.Direction.ASC, "archivoNombre")
        );
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<CerDocumentoAdjunto> req, ExampleMatcher matcher, Example<CerDocumentoAdjunto> example) {
        return;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(CerDocumentoAdjunto bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected CerDocumentoAdjunto setCreate(CerDocumentoAdjunto bean) throws Exception {
        return bean;
    }

    protected void setSave(CerDocumentoAdjunto dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected CerDocumentoAdjunto setUploadExcel(Cell currentCell, CerDocumentoAdjunto cerDocumentoAdjunto, int contador) throws Exception {
        cerDocumentoAdjunto = super.setUploadExcel(currentCell, cerDocumentoAdjunto, contador);
        return cerDocumentoAdjunto;
    }

    protected String setSaveMasivo(CerDocumentoAdjunto dto) throws Exception {
        return "";
    }

    protected List<CerDocumentoAdjunto> setBeforeDeleteMasivo(List<CerDocumentoAdjunto> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(CerDocumentoAdjunto bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByCerCertificado(CerCertificado cerCertificado) {
        return cerCertificado.getId().toString();
    }

    protected String setGraphPieChartTituloByCerCertificado() {
        return "CerCertificado";
    }

    protected String setGraphBarChartTituloByCerCertificado() {
        return "CerCertificado";
    }

}
