/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.CerHistorial;
import com.incloud.hcp.domain.CerHistorialDetalleSap;
import com.incloud.hcp.domain.response.CerHistorialDetalleSapResponse;
import com.incloud.hcp.service.delta.CerHistorialDetalleSapDeltaService;
import com.incloud.hcp.service.impl.CerHistorialDetalleSapServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for CerHistorialDetalleSap.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class CerHistorialDetalleSapDeltaServiceImpl extends CerHistorialDetalleSapServiceImpl implements CerHistorialDetalleSapDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "descripcion"));
        return sort;
    }

    protected Sort setFind(CerHistorialDetalleSap req, ExampleMatcher matcher, Example<CerHistorialDetalleSap> example, Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "descripcion"));
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<CerHistorialDetalleSap> req, ExampleMatcher matcher, Example<CerHistorialDetalleSap> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, CerHistorialDetalleSapResponse bean, CriteriaBuilder cb,
            CriteriaQuery<CerHistorialDetalleSap> query, Root<CerHistorialDetalleSap> root) throws Exception {

        CerHistorialDetalleSap entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<CerHistorialDetalleSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<CerHistorialDetalleSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<CerHistorialDetalleSap> setAdicionalDeltaTotalPredicate(CerHistorialDetalleSapResponse bean, Root<CerHistorialDetalleSap> countRoot)
            throws Exception {
        CerHistorialDetalleSap entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<CerHistorialDetalleSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(CerHistorialDetalleSap bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected CerHistorialDetalleSap setCreate(CerHistorialDetalleSap bean) throws Exception {
        return bean;
    }

    protected void setSave(CerHistorialDetalleSap dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected CerHistorialDetalleSap setUploadExcel(Cell currentCell, CerHistorialDetalleSap cerHistorialDetalleSap, int contador) throws Exception {
        cerHistorialDetalleSap = super.setUploadExcel(currentCell, cerHistorialDetalleSap, contador);
        return cerHistorialDetalleSap;
    }

    protected String setSaveMasivo(CerHistorialDetalleSap dto) throws Exception {
        return "";
    }

    protected List<CerHistorialDetalleSap> setBeforeDeleteMasivo(List<CerHistorialDetalleSap> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(CerHistorialDetalleSap bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByCerHistorial(CerHistorial cerHistorial) {
        return cerHistorial.getId().toString();
    }

    protected String setGraphPieChartTituloByCerHistorial() {
        return "CerHistorial";
    }

    protected String setGraphBarChartTituloByCerHistorial() {
        return "CerHistorial";
    }

}
