/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.FacDocumentoAdjunto;
import com.incloud.hcp.domain.FacFactura;
import com.incloud.hcp.service.delta.FacDocumentoAdjuntoDeltaService;
import com.incloud.hcp.service.impl.FacDocumentoAdjuntoServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * A simple DTO Facility for FacDocumentoAdjunto.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class FacDocumentoAdjuntoDeltaServiceImpl extends FacDocumentoAdjuntoServiceImpl implements FacDocumentoAdjuntoDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "facFactura.id"),
                new Sort.Order(Sort.Direction.ASC, "tipoAdjunto"),
                new Sort.Order(Sort.Direction.ASC, "archivoNombre")
        );
        return sort;
    }

    protected Sort setFind(FacDocumentoAdjunto req, ExampleMatcher matcher, Example<FacDocumentoAdjunto> example, Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "facFactura.id"),
                new Sort.Order(Sort.Direction.ASC, "tipoAdjunto"),
                new Sort.Order(Sort.Direction.ASC, "archivoNombre")
        );
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<FacDocumentoAdjunto> req, ExampleMatcher matcher, Example<FacDocumentoAdjunto> example) {
        return;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(FacDocumentoAdjunto bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected FacDocumentoAdjunto setCreate(FacDocumentoAdjunto bean) throws Exception {
        return bean;
    }

    protected void setSave(FacDocumentoAdjunto dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected FacDocumentoAdjunto setUploadExcel(Cell currentCell, FacDocumentoAdjunto facDocumentoAdjunto, int contador) throws Exception {
        facDocumentoAdjunto = super.setUploadExcel(currentCell, facDocumentoAdjunto, contador);
        return facDocumentoAdjunto;
    }

    protected String setSaveMasivo(FacDocumentoAdjunto dto) throws Exception {
        return "";
    }

    protected List<FacDocumentoAdjunto> setBeforeDeleteMasivo(List<FacDocumentoAdjunto> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(FacDocumentoAdjunto bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByFacFactura(FacFactura facFactura) {
        return facFactura.getId().toString();
    }

    protected String setGraphPieChartTituloByFacFactura() {
        return "FacFactura";
    }

    protected String setGraphBarChartTituloByFacFactura() {
        return "FacFactura";
    }

}
