/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.FacFactura;
import com.incloud.hcp.domain.FacFacturaTramaSap;
import com.incloud.hcp.domain.response.FacFacturaTramaSapResponse;
import com.incloud.hcp.service.delta.FacFacturaTramaSapDeltaService;
import com.incloud.hcp.service.impl.FacFacturaTramaSapServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for FacFacturaTramaSap.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class FacFacturaTramaSapDeltaServiceImpl extends FacFacturaTramaSapServiceImpl implements FacFacturaTramaSapDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombreRfc"));
        return sort;
    }

    protected Sort setFind(FacFacturaTramaSap req, ExampleMatcher matcher, Example<FacFacturaTramaSap> example, Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "nombreRfc"));
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<FacFacturaTramaSap> req, ExampleMatcher matcher, Example<FacFacturaTramaSap> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, FacFacturaTramaSapResponse bean, CriteriaBuilder cb,
            CriteriaQuery<FacFacturaTramaSap> query, Root<FacFacturaTramaSap> root) throws Exception {

        FacFacturaTramaSap entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<FacFacturaTramaSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<FacFacturaTramaSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<FacFacturaTramaSap> setAdicionalDeltaTotalPredicate(FacFacturaTramaSapResponse bean, Root<FacFacturaTramaSap> countRoot) throws Exception {
        FacFacturaTramaSap entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<FacFacturaTramaSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(FacFacturaTramaSap bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected FacFacturaTramaSap setCreate(FacFacturaTramaSap bean) throws Exception {
        return bean;
    }

    protected void setSave(FacFacturaTramaSap dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected FacFacturaTramaSap setUploadExcel(Cell currentCell, FacFacturaTramaSap facFacturaTramaSap, int contador) throws Exception {
        facFacturaTramaSap = super.setUploadExcel(currentCell, facFacturaTramaSap, contador);
        return facFacturaTramaSap;
    }

    protected String setSaveMasivo(FacFacturaTramaSap dto) throws Exception {
        return "";
    }

    protected List<FacFacturaTramaSap> setBeforeDeleteMasivo(List<FacFacturaTramaSap> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(FacFacturaTramaSap bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByFacFactura(FacFactura facFactura) {
        return facFactura.getId().toString();
    }

    protected String setGraphPieChartTituloByFacFactura() {
        return "FacFactura";
    }

    protected String setGraphBarChartTituloByFacFactura() {
        return "FacFactura";
    }

}
