/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.FacFactura;
import com.incloud.hcp.domain.FacMensajeSap;
import com.incloud.hcp.domain.response.FacMensajeSapResponse;
import com.incloud.hcp.service.delta.FacMensajeSapDeltaService;
import com.incloud.hcp.service.impl.FacMensajeSapServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for FacMensajeSap.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class FacMensajeSapDeltaServiceImpl extends FacMensajeSapServiceImpl implements FacMensajeSapDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(FacMensajeSap req, ExampleMatcher matcher, Example<FacMensajeSap> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<FacMensajeSap> req, ExampleMatcher matcher, Example<FacMensajeSap> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, FacMensajeSapResponse bean, CriteriaBuilder cb,
            CriteriaQuery<FacMensajeSap> query, Root<FacMensajeSap> root) throws Exception {

        FacMensajeSap entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<FacMensajeSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<FacMensajeSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<FacMensajeSap> setAdicionalDeltaTotalPredicate(FacMensajeSapResponse bean, Root<FacMensajeSap> countRoot) throws Exception {
        FacMensajeSap entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<FacMensajeSap, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(FacMensajeSap bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected FacMensajeSap setCreate(FacMensajeSap bean) throws Exception {
        return bean;
    }

    protected void setSave(FacMensajeSap dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected FacMensajeSap setUploadExcel(Cell currentCell, FacMensajeSap facMensajeSap, int contador) throws Exception {
        facMensajeSap = super.setUploadExcel(currentCell, facMensajeSap, contador);
        return facMensajeSap;
    }

    protected String setSaveMasivo(FacMensajeSap dto) throws Exception {
        return "";
    }

    protected List<FacMensajeSap> setBeforeDeleteMasivo(List<FacMensajeSap> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(FacMensajeSap bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByFacFactura(FacFactura facFactura) {
        return facFactura.getId().toString();
    }

    protected String setGraphPieChartTituloByFacFactura() {
        return "FacFactura";
    }

    protected String setGraphBarChartTituloByFacFactura() {
        return "FacFactura";
    }

}
