/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrMoneda;
import com.incloud.hcp.service.delta.MtrMonedaDeltaService;
import com.incloud.hcp.service.impl.MtrMonedaServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * A simple DTO Facility for MtrMoneda.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrMonedaDeltaServiceImpl extends MtrMonedaServiceImpl implements MtrMonedaDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "sigla"),
                new Sort.Order(Sort.Direction.ASC, "monedaDescrip")
        );
        return sort;
    }

    protected Sort setFind(MtrMoneda req, ExampleMatcher matcher, Example<MtrMoneda> example, Sort sort) {
        sort = Sort.by(
                new Sort.Order(Sort.Direction.ASC, "sigla"),
                new Sort.Order(Sort.Direction.ASC, "monedaDescrip")
        );
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrMoneda> req, ExampleMatcher matcher, Example<MtrMoneda> example) {
        return;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrMoneda bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrMoneda setCreate(MtrMoneda bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrMoneda dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrMoneda setUploadExcel(Cell currentCell, MtrMoneda mtrMoneda, int contador) throws Exception {
        mtrMoneda = super.setUploadExcel(currentCell, mtrMoneda, contador);
        return mtrMoneda;
    }

    protected String setSaveMasivo(MtrMoneda dto) throws Exception {
        return "";
    }

    protected List<MtrMoneda> setBeforeDeleteMasivo(List<MtrMoneda> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrMoneda bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
