/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrReemplazoFacturacion;
import com.incloud.hcp.domain.MtrSector;
import com.incloud.hcp.domain.MtrTipoGerencia;
import com.incloud.hcp.domain.MtrUsuarioFacturacion;
import com.incloud.hcp.domain.response.MtrReemplazoFacturacionResponse;
import com.incloud.hcp.service.delta.MtrReemplazoFacturacionDeltaService;
import com.incloud.hcp.service.impl.MtrReemplazoFacturacionServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MtrReemplazoFacturacion.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrReemplazoFacturacionDeltaServiceImpl extends MtrReemplazoFacturacionServiceImpl implements MtrReemplazoFacturacionDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(MtrReemplazoFacturacion req, ExampleMatcher matcher, Example<MtrReemplazoFacturacion> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrReemplazoFacturacion> req, ExampleMatcher matcher, Example<MtrReemplazoFacturacion> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MtrReemplazoFacturacionResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MtrReemplazoFacturacion> query, Root<MtrReemplazoFacturacion> root) throws Exception {

        MtrReemplazoFacturacion entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MtrReemplazoFacturacion, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MtrReemplazoFacturacion, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MtrReemplazoFacturacion> setAdicionalDeltaTotalPredicate(MtrReemplazoFacturacionResponse bean, Root<MtrReemplazoFacturacion> countRoot)
            throws Exception {
        MtrReemplazoFacturacion entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MtrReemplazoFacturacion, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrReemplazoFacturacion bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrReemplazoFacturacion setCreate(MtrReemplazoFacturacion bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrReemplazoFacturacion dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrReemplazoFacturacion setUploadExcel(Cell currentCell, MtrReemplazoFacturacion mtrReemplazoFacturacion, int contador) throws Exception {
        mtrReemplazoFacturacion = super.setUploadExcel(currentCell, mtrReemplazoFacturacion, contador);
        return mtrReemplazoFacturacion;
    }

    protected String setSaveMasivo(MtrReemplazoFacturacion dto) throws Exception {
        return "";
    }

    protected List<MtrReemplazoFacturacion> setBeforeDeleteMasivo(List<MtrReemplazoFacturacion> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrReemplazoFacturacion bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByMtrTipoGerencia(MtrTipoGerencia mtrTipoGerencia) {
        return mtrTipoGerencia.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrTipoGerencia() {
        return "MtrTipoGerencia";
    }

    protected String setGraphBarChartTituloByMtrTipoGerencia() {
        return "MtrTipoGerencia";
    }

    protected String setGraphDescripcionByMtrUsuarioFacturacion(MtrUsuarioFacturacion mtrUsuarioFacturacion) {
        return mtrUsuarioFacturacion.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrUsuarioFacturacion() {
        return "MtrUsuarioFacturacion";
    }

    protected String setGraphBarChartTituloByMtrUsuarioFacturacion() {
        return "MtrUsuarioFacturacion";
    }

    protected String setGraphDescripcionByMtrSector(MtrSector mtrSector) {
        return mtrSector.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrSector() {
        return "MtrSector";
    }

    protected String setGraphBarChartTituloByMtrSector() {
        return "MtrSector";
    }

}
