/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrTasaCambio;
import com.incloud.hcp.domain.response.MtrTasaCambioResponse;
import com.incloud.hcp.service.delta.MtrTasaCambioDeltaService;
import com.incloud.hcp.service.impl.MtrTasaCambioServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MtrTasaCambio.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrTasaCambioDeltaServiceImpl extends MtrTasaCambioServiceImpl implements MtrTasaCambioDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(MtrTasaCambio req, ExampleMatcher matcher, Example<MtrTasaCambio> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrTasaCambio> req, ExampleMatcher matcher, Example<MtrTasaCambio> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MtrTasaCambioResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MtrTasaCambio> query, Root<MtrTasaCambio> root) throws Exception {

        MtrTasaCambio entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MtrTasaCambio, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MtrTasaCambio, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MtrTasaCambio> setAdicionalDeltaTotalPredicate(MtrTasaCambioResponse bean, Root<MtrTasaCambio> countRoot) throws Exception {
        MtrTasaCambio entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MtrTasaCambio, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrTasaCambio bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrTasaCambio setCreate(MtrTasaCambio bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrTasaCambio dto) throws Exception {
        return;
    }

    protected void setDelete(Integer id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrTasaCambio setUploadExcel(Cell currentCell, MtrTasaCambio mtrTasaCambio, int contador) throws Exception {
        mtrTasaCambio = super.setUploadExcel(currentCell, mtrTasaCambio, contador);
        return mtrTasaCambio;
    }

    protected String setSaveMasivo(MtrTasaCambio dto) throws Exception {
        return "";
    }

    protected List<MtrTasaCambio> setBeforeDeleteMasivo(List<MtrTasaCambio> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrTasaCambio bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/


}
