/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.Curso;
import com.incloud.hcp.domain.Horario;
import com.incloud.hcp.domain.response.HorarioResponse;
import com.incloud.hcp.repository.delta.HorarioDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.HorarioDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class HorarioRest extends JPACustomRest<HorarioResponse, Horario, Integer> {

    @Autowired
    protected HorarioDeltaService horarioDeltaService;

    @Autowired
    protected HorarioDeltaRepository horarioDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "Horario";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final Horario createInstance() {
        Horario horario = new Horario();
        return horario;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo curso.
    */
    @ApiOperation(value = "Contador de registros para el atributo curso", produces = "application/json")
    @PostMapping(value = "/countByCurso", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByCurso(@RequestBody @Valid Curso curso, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByCurso");
        try {
            return Optional.ofNullable(this.horarioDeltaService.countByCurso(curso)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo curso.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo curso", produces = "application/json")
    @GetMapping(value = "/graphByCurso", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByCurso() throws URISyntaxException {
        log.debug("Ingresando graphByCurso");
        try {
            return Optional.ofNullable(this.horarioDeltaService.graphByCurso()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
