/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MigCertificado;
import com.incloud.hcp.domain.response.MigCertificadoResponse;
import com.incloud.hcp.repository.delta.MigCertificadoDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MigCertificadoRest extends JPACustomRest<MigCertificadoResponse, MigCertificado, Integer> {

    @Autowired
    protected MigCertificadoDeltaRepository migCertificadoDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MigCertificado";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MigCertificado createInstance() {
        MigCertificado migCertificado = new MigCertificado();
        return migCertificado;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
