/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.MtrMoneda;
import com.incloud.hcp.domain.MtrRangoMontoEstrategia;
import com.incloud.hcp.domain.response.MtrRangoMontoEstrategiaResponse;
import com.incloud.hcp.repository.delta.MtrRangoMontoEstrategiaDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.MtrRangoMontoEstrategiaDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class MtrRangoMontoEstrategiaRest extends JPACustomRest<MtrRangoMontoEstrategiaResponse, MtrRangoMontoEstrategia, Integer> {

    @Autowired
    protected MtrRangoMontoEstrategiaDeltaService mtrRangoMontoEstrategiaDeltaService;

    @Autowired
    protected MtrRangoMontoEstrategiaDeltaRepository mtrRangoMontoEstrategiaDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrRangoMontoEstrategia";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrRangoMontoEstrategia createInstance() {
        MtrRangoMontoEstrategia mtrRangoMontoEstrategia = new MtrRangoMontoEstrategia();
        return mtrRangoMontoEstrategia;
    }

    /**
     * Find by por descripcion
     */
    @ApiOperation(value = "Busca registro de tipo <T> en base a descripcion", produces = "application/json")
    @GetMapping(value = "/_getByDescripcion/{descripcion}", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<MtrRangoMontoEstrategia> getByDescripcion(@PathVariable String descripcion) throws URISyntaxException {
        log.debug(this.NOMBRE_CLASE + " - Ingresando getByDescripcion: " + descripcion);
        try {
            return Optional.ofNullable(this.mtrRangoMontoEstrategiaDeltaRepository.getByDescripcion(descripcion))
                    .map(bean -> new ResponseEntity<>(bean, HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo mtrMoneda.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrMoneda", produces = "application/json")
    @PostMapping(value = "/countByMtrMoneda", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrMoneda(@RequestBody @Valid MtrMoneda mtrMoneda, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrMoneda");
        try {
            return Optional.ofNullable(this.mtrRangoMontoEstrategiaDeltaService.countByMtrMoneda(mtrMoneda)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrMoneda.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrMoneda", produces = "application/json")
    @GetMapping(value = "/graphByMtrMoneda", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrMoneda() throws URISyntaxException {
        log.debug("Ingresando graphByMtrMoneda");
        try {
            return Optional.ofNullable(this.mtrRangoMontoEstrategiaDeltaService.graphByMtrMoneda()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
