/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrTasaCambio;
import com.incloud.hcp.domain.response.MtrTasaCambioResponse;
import com.incloud.hcp.repository.delta.MtrTasaCambioDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.MtrTasaCambioDeltaService;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrTasaCambioRest extends JPACustomRest<MtrTasaCambioResponse, MtrTasaCambio, Integer> {

    @Autowired
    protected MtrTasaCambioDeltaService mtrTasaCambioDeltaService;

    @Autowired
    protected MtrTasaCambioDeltaRepository mtrTasaCambioDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrTasaCambio";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrTasaCambio createInstance() {
        MtrTasaCambio mtrTasaCambio = new MtrTasaCambio();
        return mtrTasaCambio;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
