/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.*;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;

import java.util.List;

@NoRepositoryBean
public interface CerFirmaRepository extends JPACustomRepository<CerFirma, Integer> {

    default List<CerFirma> findCompletePaginated(String query, int maxResults) {
        CerFirma probe = new CerFirma();
        //probe.setEbeln(query);
        probe.setEbeln(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(CerFirma_.ebeln.getName(), match -> match.ignoreCase().startsWith());

        Page<CerFirma> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByCerNotaPedido(@Param("cerNotaPedido") CerNotaPedido cerNotaPedido);

    Long countByMtrAprobador(@Param("mtrAprobador") MtrAprobador mtrAprobador);

    Long countByMtrTipoFirma(@Param("mtrTipoFirma") MtrTipoFirma mtrTipoFirma);

}
