/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.FacFactura;
import com.incloud.hcp.domain.FacFacturaTramaSap;
import com.incloud.hcp.domain.FacFacturaTramaSap_;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;

import java.util.List;

@NoRepositoryBean
public interface FacFacturaTramaSapRepository extends JPACustomRepository<FacFacturaTramaSap, Integer> {

    default List<FacFacturaTramaSap> findCompletePaginated(String query, int maxResults) {
        FacFacturaTramaSap probe = new FacFacturaTramaSap();
        //probe.setNombreRfc(query);
        probe.setNombreRfc(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(FacFacturaTramaSap_.nombreRfc.getName(), match -> match.ignoreCase().startsWith());

        Page<FacFacturaTramaSap> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByFacFactura(@Param("facFactura") FacFactura facFactura);

}
