/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.MtrCuentaImputacion;
import com.incloud.hcp.domain.MtrCuentaImputacion_;
import com.incloud.hcp.domain.MtrSociedad;
import com.incloud.hcp.domain.MtrTipoImputacion;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;

import java.util.List;

@NoRepositoryBean
public interface MtrCuentaImputacionRepository extends JPACustomRepository<MtrCuentaImputacion, Integer> {

    /**
     * Return the persistent instance of {@link MtrCuentaImputacion} with the given unique property value codigoCuentaImputacion,
     * or null if there is no such persistent instance.
     *
     * @param codigoCuentaImputacion the unique value
     * @return the corresponding {@link MtrCuentaImputacion} persistent instance or null
     */
    @RestResource(path = "/getByCodigoCuentaImputacion")
    MtrCuentaImputacion getByCodigoCuentaImputacion(@Param("codigoCuentaImputacion") String codigoCuentaImputacion);

    /**
     * Return the persistent instance of {@link MtrCuentaImputacion} with the given unique property value descripcion,
     * or null if there is no such persistent instance.
     *
     * @param descripcion the unique value
     * @return the corresponding {@link MtrCuentaImputacion} persistent instance or null
     */
    @RestResource(path = "/getByDescripcion")
    MtrCuentaImputacion getByDescripcion(@Param("descripcion") String descripcion);

    default List<MtrCuentaImputacion> findCompletePaginated(String query, int maxResults) {
        MtrCuentaImputacion probe = new MtrCuentaImputacion();
        //probe.setDescripcion(query);
        probe.setDescripcion(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(MtrCuentaImputacion_.descripcion.getName(), match -> match.ignoreCase().startsWith());

        Page<MtrCuentaImputacion> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByMtrTipoImputacion(@Param("mtrTipoImputacion") MtrTipoImputacion mtrTipoImputacion);

    Long countByMtrSociedad(@Param("mtrSociedad") MtrSociedad mtrSociedad);

}
