/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.MtrEstrategiaFacturacion;
import com.incloud.hcp.domain.MtrEstrategiaFacturacionFirma;
import com.incloud.hcp.domain.MtrSector;
import com.incloud.hcp.domain.MtrTipoGerencia;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;

import java.util.List;

@NoRepositoryBean
public interface MtrEstrategiaFacturacionFirmaRepository extends JPACustomRepository<MtrEstrategiaFacturacionFirma, Integer> {

    default List<MtrEstrategiaFacturacionFirma> findCompletePaginated(String query, int maxResults) {
        MtrEstrategiaFacturacionFirma probe = new MtrEstrategiaFacturacionFirma();
        ExampleMatcher matcher = ExampleMatcher.matching() //
        ;

        Page<MtrEstrategiaFacturacionFirma> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByMtrEstrategiaFacturacion(@Param("mtrEstrategiaFacturacion") MtrEstrategiaFacturacion mtrEstrategiaFacturacion);

    Long countByMtrTipoGerencia(@Param("mtrTipoGerencia") MtrTipoGerencia mtrTipoGerencia);

    Long countByMtrSector(@Param("mtrSector") MtrSector mtrSector);

}
