/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.MtrSector;
import com.incloud.hcp.domain.MtrTipoGerencia;
import com.incloud.hcp.domain.MtrUsuarioFacturacion;
import com.incloud.hcp.domain.MtrUsuarioFacturacion_;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RestResource;

import java.util.List;

@NoRepositoryBean
public interface MtrUsuarioFacturacionRepository extends JPACustomRepository<MtrUsuarioFacturacion, Integer> {

    /**
     * Return the persistent instance of {@link MtrUsuarioFacturacion} with the given unique property value codigoUsuarioSap,
     * or null if there is no such persistent instance.
     *
     * @param codigoUsuarioSap the unique value
     * @return the corresponding {@link MtrUsuarioFacturacion} persistent instance or null
     */
    @RestResource(path = "/getByCodigoUsuarioSap")
    MtrUsuarioFacturacion getByCodigoUsuarioSap(@Param("codigoUsuarioSap") String codigoUsuarioSap);

    /**
     * Return the persistent instance of {@link MtrUsuarioFacturacion} with the given unique property value email,
     * or null if there is no such persistent instance.
     *
     * @param email the unique value
     * @return the corresponding {@link MtrUsuarioFacturacion} persistent instance or null
     */
    @RestResource(path = "/getByEmail")
    MtrUsuarioFacturacion getByEmail(@Param("email") String email);

    default List<MtrUsuarioFacturacion> findCompletePaginated(String query, int maxResults) {
        MtrUsuarioFacturacion probe = new MtrUsuarioFacturacion();
        //probe.setEmail(query);
        probe.setEmail(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(MtrUsuarioFacturacion_.email.getName(), match -> match.ignoreCase().startsWith());

        Page<MtrUsuarioFacturacion> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByMtrTipoGerencia(@Param("mtrTipoGerencia") MtrTipoGerencia mtrTipoGerencia);

    Long countByMtrSector(@Param("mtrSector") MtrSector mtrSector);

}
