/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntitydeltaRepository.java.e.vm
 */
package com.incloud.hcp.repository.delta;

import com.incloud.hcp.domain.CerCertificado;
import com.incloud.hcp.domain.CerCertificadoFirma;
import com.incloud.hcp.domain.CerFirma;
import com.incloud.hcp.repository.CerCertificadoFirmaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface CerCertificadoFirmaDeltaRepository extends CerCertificadoFirmaRepository {


    @Query("select u from CerCertificadoFirma u " +
            "where u.cerFirma.mtrAprobador.id =?1 " +
            "  and u.cerCertificado.mtrEstado.id =?2 " +
            "  and u.cerFirma.mtrTipoFirma.id =?3 " )
    List<CerCertificadoFirma> findByAprobador(Integer mtrAprobadorId, Integer mtrEstadoId, Integer mtrTipoFirmaId);


    List<CerCertificadoFirma> findByCerCertificado(CerCertificado cerCertificado);

    List<CerCertificadoFirma> findByCerFirma(CerFirma cerFirma);

    @Query("select u from CerCertificadoFirma u where u.cerCertificado.id = ?1 and u.cerFirma.mtrTipoFirma.codigoTipoFirma = ?2")
    List<CerCertificadoFirma> findByCertificadoAndTipoFirma(Integer cerCertificadoId, String codigoTipoFirma);

    @Modifying
    @Query("DELETE FROM CerCertificadoFirma cf WHERE cf.cerFirma.id = ?1")
    void deleteByFirmaId(Integer id);
}
