/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntitydeltaRepository.java.e.vm
 */
package com.incloud.hcp.repository.delta;

import com.incloud.hcp.domain.CerHistorial;
import com.incloud.hcp.repository.CerHistorialRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface CerHistorialDeltaRepository extends CerHistorialRepository {

    @Query("select h from CerHistorial h where h.cerCertificado.id = ?1 order by h.id desc")
    List<CerHistorial> findByIdCertificadox(Integer idCertificado);
}
