/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntitydeltaRepository.java.e.vm
 */
package com.incloud.hcp.repository.delta;

import com.incloud.hcp.domain.CerNotaPedido;
import com.incloud.hcp.domain.CerNotaPedidoDetalle;
import com.incloud.hcp.repository.CerNotaPedidoDetalleRepository;
import org.springframework.data.jpa.repository.Query;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public interface CerNotaPedidoDetalleDeltaRepository extends CerNotaPedidoDetalleRepository {


    @Query("select u from CerNotaPedidoDetalle u where u.cerNotaPedido.id = ?1 " +
            "and u.idPadre is null " +
            "order by u.posicionSap, u.extrow")
    List<CerNotaPedidoDetalle> findByDetalleSoloPosiciones(Integer cerNotaPedidoId);

    @Query("select u from CerNotaPedidoDetalle u where u.id = ?1 " +
            "and u.idPadre is null " +
            "order by u.posicionSap, u.extrow")
    CerNotaPedidoDetalle findByDetallePadre(Integer idPadre);


    @Query("select u from CerNotaPedidoDetalle u where u.cerNotaPedido.id = ?1 " +
            "and u.idPadre = ?2 " +
            "order by u.posicionSap, u.extrow")
    List<CerNotaPedidoDetalle> findByDetalleSubPosicion(Integer cerNotaPedidoId, Integer idPadre);

    @Query("select u from CerNotaPedidoDetalle u where " +
            "u.posicionSap = ?1 and u.ebeln = ?2 " )
    CerNotaPedidoDetalle getByPedPos(String ebelp, String ebeln);

    List<CerNotaPedidoDetalle> findByCerNotaPedidoOrderByFechaEntrega(CerNotaPedido cerNotaPedido);

    List<CerNotaPedidoDetalle> findByCerNotaPedidoOrderByNuevaFechaEntrega(CerNotaPedido cerNotaPedido);

    List<CerNotaPedidoDetalle> findByCerNotaPedido(CerNotaPedido cerNotaPedido);

    List<CerNotaPedidoDetalle> findByCerNotaPedidoAndFechaEntrega(CerNotaPedido cerNotaPedido, Date fechaEntrega);

    List<CerNotaPedidoDetalle> findByCerNotaPedidoAndNuevaFechaEntrega(
            CerNotaPedido cerNotaPedido, Date fechaEntrega);

    @Query("select distinct u.fechaEntrega from CerNotaPedidoDetalle u " +
            "where u.cerNotaPedido = ?1 " +
            "order by u.fechaEntrega")
    List<Date> findByCerNotaPedidoDistintFechaEntrega(CerNotaPedido cerNotaPedidoId);

    @Query("select distinct u.nuevaFechaEntrega from CerNotaPedidoDetalle u " +
            "where u.cerNotaPedido.id = ?1 " +
            "order by u.nuevaFechaEntrega")
    List<Date> findByCerNotaPedidoDistintNuevaFechaEntrega(Integer cerNotaPedidoId);

    @Query(nativeQuery = true,
            value="select sum(u.cantidad_requerida - IFNULL(u.cantidad_entregada,0)) from Cer_Nota_Pedido_Detalle u " +
            "where u.cer_nota_pedido_id = ?1 ")
    BigDecimal sumarCantidadPendiente(Integer cerNotaPedidoId);


    @Query("select u from CerNotaPedidoDetalle u where u.cerNotaPedido.id = ?1 " +
            "and u.extrow = ?2 " +
            "and u.posicionSap = ?3 ")
    CerNotaPedidoDetalle findByDetalleSubPosicionServicio(Integer cerNotaPedidoId, String extRow, String posicion);

}
