/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntitydeltaRepository.java.e.vm
 */
package com.incloud.hcp.repository.delta;

import com.incloud.hcp.domain.FacEstrategiaIteracion;
import com.incloud.hcp.domain.FacFactura;
import com.incloud.hcp.repository.FacEstrategiaIteracionRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface FacEstrategiaIteracionDeltaRepository extends FacEstrategiaIteracionRepository {

    @Query("select max(u.nroIteracion) from FacEstrategiaIteracion u " +
            "where u.facFactura.id = ?1" )
    Integer getMaximoInteracionFactura(Integer facFacturaId);

    @Query("select u from FacEstrategiaIteracion u " +
            "where u.facFactura.id = ?1 and u.nroIteracion = ?2" )
    FacEstrategiaIteracion getByFacturaNroIteracion(Integer facFacturaId, Integer nroIteracion);

    List<FacEstrategiaIteracion> findByFacFactura(FacFactura facFactura);

    @Query("select u.facFactura from FacEstrategiaIteracion u " +
            "where u.facFactura.id in ?1 " +
            "and u.mtrUsuarioFacturacionAprobador0.id = ?2 " +
            "and u.activo = 'S'" )
    List<FacFactura> findFacturaAprobarRechazarAprobador0(List<Integer> facFacturaIdList, Integer mtrUsuarioFacturacionAprobador0Id);


    @Query("select u from FacEstrategiaIteracion u " +
            "where u.facFactura.mtrEstado.id = ?2 " +
            "and u.activo = 'S'" )
    List<FacEstrategiaIteracion> findFacturaAprobarRechazarCupaPorAprobar(
            Integer mtrEstadoId);


    @Query("select u from FacEstrategiaIteracion u " +
            "where u.indAprobacionRechazoCupa = ?1 " +
            "and u.indAprobacionRechazoAprobador0 = ?2 " +
            "and u.facFactura.mtrEstado.id = ?3 " +
            "and u.mtrUsuarioFacturacionAprobador0 is not null " +
            "and u.activo = 'S'" )
    List<FacEstrategiaIteracion> findFacturaAprobarRechazarAprobador0PorAprobar(
            String indicadorCupa,
            String indicadorAprobador0,
            Integer mtrEstadoId);


    @Query("select u from FacEstrategiaIteracion u " +
            "where u.indAprobacionRechazoCupa = ?1 " +
            "and u.indAprobacionRechazoAprobador0 = ?2 " +
            "and u.indAprobacionRechazoFirma = ?3 " +
            "and u.facFactura.mtrEstado.id = ?4 " +
            "and u.activo = 'S'" )
    List<FacEstrategiaIteracion> findFacturaAprobarRechazarFirmantePorAprobar(
            String indicadorCupa,
            String indicadorAprobador0,
            String indicadorFirmante,
            Integer mtrEstadoId);

}
