/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntitydeltaRepository.java.e.vm
 */
package com.incloud.hcp.repository.delta;

import com.incloud.hcp.domain.MtrEstado;
import com.incloud.hcp.repository.MtrEstadoRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface MtrEstadoDeltaRepository extends MtrEstadoRepository {

    MtrEstado getByCodigoAgrupadoAndCodigoEstado(String codigoAgrupado, String codigoEstado);

    @Query("select e from MtrEstado e where e.codigoAgrupado = ?1 and e.codigoEstado = ?2")
    MtrEstado getByCodeGrupoAndCodeEstado(String codAgrupado, String codigoSap);

    @Query("select e from MtrEstado e where e.codigoAgrupado = ?1 and e.codigoEstado <> ?2")
    List<MtrEstado> getByCodeGrupoAndNotCodeEstado(String codAgrupado, String codigoSap);

    @Query("select e.id from MtrEstado e where e.codigoAgrupado = ?1 and e.codigoEstado <> ?2")
    List<Integer> getIdByCodeGrupoAndNotCodeEstado(String codAgrupado, String codigoSap);

}
