/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/support/AutoCompleteQuery.java.p.vm
 */
package com.incloud.hcp.rest.support;

public class AutoCompleteQuery {
    public String query;
    public int maxResults;
}
