INSERT INTO APP_PARAMETRIA
(PARAMETRIA_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, DESCRIPTION, LABEL, MODULO, STATUS, VALUE_1, VALUE_2, VALUE_3)
VALUES(SEQ_APP_PARAMETRIA.nextval, NULL, NULL, NULL, NULL, 'Tipo Factura con/sin certificado', NULL, 'FAC_TIPO_CERTI', '1', 'Factura con Certicado (PO)', 'PO', '1');

INSERT INTO APP_PARAMETRIA
(PARAMETRIA_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, DESCRIPTION, LABEL, MODULO, STATUS, VALUE_1, VALUE_2, VALUE_3)
VALUES(SEQ_APP_PARAMETRIA.nextval, NULL, NULL, NULL, NULL, 'Tipo Factura con/sin certificado', NULL, 'FAC_TIPO_CERTI', '1', 'Factura sin Certicado (PF)', 'PF', '0');


INSERT INTO APP_PARAMETRIA
(PARAMETRIA_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, DESCRIPTION, LABEL, MODULO, STATUS, VALUE_1, VALUE_2, VALUE_3)
VALUES(SEQ_APP_PARAMETRIA.nextval, NULL, NULL, NULL, NULL, 'Tipo Factura Exterior', NULL, 'FAC_TIPO_CON_CERTI', '1', 'Factura Exterior con Certicado (PS)', 'PS', '1');

INSERT INTO APP_PARAMETRIA
(PARAMETRIA_ID, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, DESCRIPTION, LABEL, MODULO, STATUS, VALUE_1, VALUE_2, VALUE_3)
VALUES(SEQ_APP_PARAMETRIA.nextval, NULL, NULL, NULL, NULL, 'Tipo Factura Exterior', NULL, 'FAC_TIPO_CON_CERTI', '1', 'Factura Exterior sin Certicado (PE)', 'PE', '0');




