DROP PROCEDURE SPLIT_AT_CHARACTER;
CREATE PROCEDURE SPLIT_AT_CHARACTER(IN IP_STR VARCHAR(4000),OUT OUTTAB SPLIT_TYPE) 
LANGUAGE SQLSCRIPT
AS
TEMP_STR VARCHAR(100) := :IP_STR || '///';
OUT_VAR VARCHAR(4000) ARRAY;
POS INTEGER :=1;
FLAG INTEGER := 1;
LEFT_STR VARCHAR(4000);
BEGIN
 WHILE(LENGTH(:TEMP_STR) > 0 ) DO
  LEFT_STR := SUBSTR_BEFORE (:TEMP_STR,'///');
  TEMP_STR := SUBSTR_AFTER (:TEMP_STR,:LEFT_STR || '///');
  OUT_VAR[POS] := LEFT_STR;
  POS := :POS + 1;
 END WHILE;
 OUTTAB = UNNEST(:OUT_VAR) AS ("SPLIT");
END;