/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.math.BigDecimal;
import java.util.Date;

@StaticMetamodel(CerCertificadoDetalle.class)
public abstract class CerCertificadoDetalle_ {

    // Raw attributes
    public static volatile SingularAttribute<CerCertificadoDetalle, Integer> id;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> subpackno;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> rango;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> numOrden;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> nivelEstructura;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> indicadorItemAdici;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> ctaContable;
    public static volatile SingularAttribute<CerCertificadoDetalle, BigDecimal> precioUnitario;
    public static volatile SingularAttribute<CerCertificadoDetalle, BigDecimal> descuento;
    public static volatile SingularAttribute<CerCertificadoDetalle, BigDecimal> cantidadTotal;
    public static volatile SingularAttribute<CerCertificadoDetalle, BigDecimal> cantidadPendiente;
    public static volatile SingularAttribute<CerCertificadoDetalle, BigDecimal> cantidadAprobada;
    public static volatile SingularAttribute<CerCertificadoDetalle, BigDecimal> totalLinea;
    public static volatile SingularAttribute<CerCertificadoDetalle, BigDecimal> totalLineaAjustado;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> asignServicio;
    public static volatile SingularAttribute<CerCertificadoDetalle, String> auxiliar;
    public static volatile SingularAttribute<CerCertificadoDetalle, Date> fechaCreacionMigo;

    // Many to one
    public static volatile SingularAttribute<CerCertificadoDetalle, MtrCuentaMayor> mtrCuentaMayor;
    public static volatile SingularAttribute<CerCertificadoDetalle, MtrCuentaImputacion> mtrCuentaImputacion;
    public static volatile SingularAttribute<CerCertificadoDetalle, CerNotaPedidoDetalle> cerNotaPedidoDetalle;
    public static volatile SingularAttribute<CerCertificadoDetalle, CerCertificado> cerCertificado;
}
