/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.util.Date;

@StaticMetamodel(CerCertificadoFirma.class)
public abstract class CerCertificadoFirma_ {

    // Raw attributes
    public static volatile SingularAttribute<CerCertificadoFirma, Integer> id;
    public static volatile SingularAttribute<CerCertificadoFirma, String> descripcion;
    public static volatile SingularAttribute<CerCertificadoFirma, Date> fechaAprobacion;
    public static volatile SingularAttribute<CerCertificadoFirma, String> indAprobacionRechazo;

    // Many to one
    public static volatile SingularAttribute<CerCertificadoFirma, CerCertificado> cerCertificado;
    public static volatile SingularAttribute<CerCertificadoFirma, CerFirma> cerFirma;
}
