/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "cer_firma", uniqueConstraints = {
        @UniqueConstraint(name = "cer_firma_ak01", columnNames = { "cer_nota_pedido_id", "mtr_tipo_firma_id", "mtr_aprobador_id" }) })
//@Audited
//@AuditTable("_audi_cer_firma")
public class CerFirma extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(CerFirma.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String ebeln;


    // Many to one
    private CerNotaPedido cerNotaPedido;
    private MtrAprobador mtrAprobador;
    private MtrAprobador mtrReemplazo;
    private MtrTipoFirma mtrTipoFirma;


    @Override
    public String entityClassName() {
        return CerFirma.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "cer_firma_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_cer_firma")
    @Id
    @SequenceGenerator(name = "seq_cer_firma", sequenceName = "seq_cer_firma", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public CerFirma id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [ebeln] ------------------------

    @Size(max = 20, message = "{message.cerFirma.ebeln.sizeMax} {max} {message.caracter}")
    @Column(name = "ebeln", length = 20)
    public String getEbeln() {
        return ebeln;
    }

    public void setEbeln(String ebeln) {
        this.ebeln = ebeln;
    }

    public CerFirma ebeln(String ebeln) {
        setEbeln(ebeln);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CerFirma.cerNotaPedido ==> CerNotaPedido.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "cer_nota_pedido_id", nullable = false)
    @ManyToOne
    public CerNotaPedido getCerNotaPedido() {
        return cerNotaPedido;
    }

    /**
     * Set the {@link #cerNotaPedido} without adding this CerFirma instance on the passed {@link #cerNotaPedido}
     */
    public void setCerNotaPedido(CerNotaPedido cerNotaPedido) {
        this.cerNotaPedido = cerNotaPedido;
    }

    public CerFirma cerNotaPedido(CerNotaPedido cerNotaPedido) {
        setCerNotaPedido(cerNotaPedido);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CerFirma.mtrAprobador ==> MtrAprobador.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "mtr_aprobador_id", nullable = false)
    @ManyToOne
    public MtrAprobador getMtrAprobador() {
        return mtrAprobador;
    }

    /**
     * Set the {@link #mtrAprobador} without adding this CerFirma instance on the passed {@link #mtrAprobador}
     */
    public void setMtrAprobador(MtrAprobador mtrAprobador) {
        this.mtrAprobador = mtrAprobador;
    }

    public CerFirma mtrAprobador(MtrAprobador mtrAprobador) {
        setMtrAprobador(mtrAprobador);
        return this;
    }

    @JoinColumn(name = "mtr_reemplazo_id", nullable = true)
    @ManyToOne
    public MtrAprobador getMtrReemplazo() {
        return mtrReemplazo;
    }

    /**
     * Set the {@link #mtrAprobador} without adding this CerFirma instance on the passed {@link #mtrAprobador}
     */
    public void setMtrReemplazo(MtrAprobador mtrReemplazo) {
        this.mtrReemplazo = mtrReemplazo;
    }

    public CerFirma mtrReemplazo(MtrAprobador mtrReemplazo) {
        setMtrReemplazo(mtrReemplazo);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CerFirma.mtrTipoFirma ==> MtrTipoFirma.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "mtr_tipo_firma_id", nullable = false)
    @ManyToOne
    public MtrTipoFirma getMtrTipoFirma() {
        return mtrTipoFirma;
    }

    /**
     * Set the {@link #mtrTipoFirma} without adding this CerFirma instance on the passed {@link #mtrTipoFirma}
     */
    public void setMtrTipoFirma(MtrTipoFirma mtrTipoFirma) {
        this.mtrTipoFirma = mtrTipoFirma;
    }

    public CerFirma mtrTipoFirma(MtrTipoFirma mtrTipoFirma) {
        setMtrTipoFirma(mtrTipoFirma);
        return this;
    }

    /**
     * Apply the default values.
     */
    public CerFirma withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof CerFirma && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this CerFirma instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("cerNotaPedido", getCerNotaPedido()) //    
                .add("mtrTipoFirma", getMtrTipoFirma()) //    
                .add("mtrAprobador", getMtrAprobador()) //    
                .add("ebeln", getEbeln()) //
                .toString();
    }
}
