/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.util.Date;

@StaticMetamodel(CerHistorial.class)
public abstract class CerHistorial_ {

    // Raw attributes
    public static volatile SingularAttribute<CerHistorial, Integer> id;
    public static volatile SingularAttribute<CerHistorial, String> descripcion;
    public static volatile SingularAttribute<CerHistorial, String> usuarioHistoral;
    public static volatile SingularAttribute<CerHistorial, Date> fechaHistorial;
    public static volatile SingularAttribute<CerHistorial, String> nroDocumentoSapAsociado;
    public static volatile SingularAttribute<CerHistorial, String> indSgmm;

    // Many to one
    public static volatile SingularAttribute<CerHistorial, MtrEstado> mtrEstado;
    public static volatile SingularAttribute<CerHistorial, CerCertificado> cerCertificado;
}
