/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.math.BigDecimal;

@StaticMetamodel(MigCertificadoDetalle.class)
public abstract class MigCertificadoDetalle_ {

    // Raw attributes
    public static volatile SingularAttribute<MigCertificadoDetalle, Integer> id;
    public static volatile SingularAttribute<MigCertificadoDetalle, Integer> posicion;
    public static volatile SingularAttribute<MigCertificadoDetalle, String> moneda;
    public static volatile SingularAttribute<MigCertificadoDetalle, String> descripcion;
    public static volatile SingularAttribute<MigCertificadoDetalle, String> unidadMedida;
    public static volatile SingularAttribute<MigCertificadoDetalle, String> cuentaContable;
    public static volatile SingularAttribute<MigCertificadoDetalle, String> ccAfeOrden;
    public static volatile SingularAttribute<MigCertificadoDetalle, BigDecimal> precioUnitario;
    public static volatile SingularAttribute<MigCertificadoDetalle, BigDecimal> cantidadEntregada;
    public static volatile SingularAttribute<MigCertificadoDetalle, BigDecimal> totalLinea;
    public static volatile SingularAttribute<MigCertificadoDetalle, String> hojaServicio;

    // Many to one
    public static volatile SingularAttribute<MigCertificadoDetalle, MigCertificado> migCertificado;
}
