/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "mtr_clase_documento")
//@Audited
//@AuditTable("_audi_mtr_clase_documento")
public class MtrClaseDocumento extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MtrClaseDocumento.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String codigoSap;
    private String descripcion;
    private String estado;

    @Override
    public String entityClassName() {
        return MtrClaseDocumento.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "mtr_clase_documento_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_mtr_clase_documento")
    @Id
    @SequenceGenerator(name = "seq_mtr_clase_documento", sequenceName = "seq_mtr_clase_documento", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public MtrClaseDocumento id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [codigoSap] ------------------------

    @NotEmpty(message = "{message.mtrClaseDocumento.codigoSap.requerido}")
    @Size(max = 4, message = "{message.mtrClaseDocumento.codigoSap.sizeMax} {max} {message.caracter}")
    @Column(name = "codigo_sap", nullable = false, unique = true, length = 4)
    public String getCodigoSap() {
        return codigoSap;
    }

    public void setCodigoSap(String codigoSap) {
        this.codigoSap = codigoSap;
    }

    public MtrClaseDocumento codigoSap(String codigoSap) {
        setCodigoSap(codigoSap);
        return this;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.mtrClaseDocumento.descripcion.requerido}")
    @Size(max = 200, message = "{message.mtrClaseDocumento.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "descripcion", nullable = false, unique = true, length = 200)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public MtrClaseDocumento descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [estado] ------------------------

    @NotEmpty(message = "{message.mtrClaseDocumento.estado.requerido}")
    @Size(max = 1, message = "{message.mtrClaseDocumento.estado.sizeMax} {max} {message.caracter}")
    @Column(name = "estado", nullable = false, length = 1)
    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public MtrClaseDocumento estado(String estado) {
        setEstado(estado);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MtrClaseDocumento withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MtrClaseDocumento && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getDescripcion());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this MtrClaseDocumento instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("codigoSap", getCodigoSap()) //
                .add("descripcion", getDescripcion()) //
                .add("estado", getEstado()) //
                .toString();
    }
}
