/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "mtr_tipo_informacion_noticia")
//@Audited
//@AuditTable("_audi_mtr_tipo_informacion_noticia")
public class MtrTipoInformacionNoticia extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MtrTipoInformacionNoticia.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String carpetaId;
    private String descripcion;
    private String iconText;

    @Override
    public String entityClassName() {
        return MtrTipoInformacionNoticia.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "mtr_tipo_informacion_noticia_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_mtr_tipo_informacion_noticia")
    @Id
    @SequenceGenerator(name = "seq_mtr_tipo_informacion_noticia", sequenceName = "seq_mtr_tipo_informacion_noticia", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public MtrTipoInformacionNoticia id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [carpetaId] ------------------------

    @Size(max = 60, message = "{message.mtrTipoInformacionNoticia.carpetaId.sizeMax} {max} {message.caracter}")
    @Column(name = "carpeta_id", length = 60)
    public String getCarpetaId() {
        return carpetaId;
    }

    public void setCarpetaId(String carpetaId) {
        this.carpetaId = carpetaId;
    }

    public MtrTipoInformacionNoticia carpetaId(String carpetaId) {
        setCarpetaId(carpetaId);
        return this;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.mtrTipoInformacionNoticia.descripcion.requerido}")
    @Size(max = 60, message = "{message.mtrTipoInformacionNoticia.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "descripcion", nullable = false, unique = true, length = 60)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public MtrTipoInformacionNoticia descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [iconText] ------------------------

    @Size(max = 60, message = "{message.mtrTipoInformacionNoticia.iconText.sizeMax} {max} {message.caracter}")
    @Column(name = "icon_text", length = 60)
    public String getIconText() {
        return iconText;
    }

    public void setIconText(String iconText) {
        this.iconText = iconText;
    }

    public MtrTipoInformacionNoticia iconText(String iconText) {
        setIconText(iconText);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MtrTipoInformacionNoticia withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MtrTipoInformacionNoticia && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getDescripcion());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this MtrTipoInformacionNoticia instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("carpetaId", getCarpetaId()) //
                .add("descripcion", getDescripcion()) //
                .add("iconText", getIconText()) //
                .toString();
    }
}
