/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "mtr_tipo_firma")
//@Audited
//@AuditTable("_audi_mtr_tipo_firma")
public class MtrTipoFirma extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MtrTipoFirma.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Integer id;
    private String codigoTipoFirma;
    private String descripcion;
    private Integer orden;

    @Override
    public String entityClassName() {
        return MtrTipoFirma.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "mtr_tipo_firma_id", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_mtr_tipo_firma")
    @Id
    @SequenceGenerator(name = "seq_mtr_tipo_firma", sequenceName = "seq_mtr_tipo_firma", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public MtrTipoFirma id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [codigoTipoFirma] ------------------------

    @NotEmpty(message = "{message.mtrTipoFirma.codigoTipoFirma.requerido}")
    @Size(max = 2, message = "{message.mtrTipoFirma.codigoTipoFirma.sizeMax} {max} {message.caracter}")
    @Column(name = "codigo_tipo_firma", nullable = false, unique = true, length = 2)
    public String getCodigoTipoFirma() {
        return codigoTipoFirma;
    }

    public void setCodigoTipoFirma(String codigoTipoFirma) {
        this.codigoTipoFirma = codigoTipoFirma;
    }

    public MtrTipoFirma codigoTipoFirma(String codigoTipoFirma) {
        setCodigoTipoFirma(codigoTipoFirma);
        return this;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.mtrTipoFirma.descripcion.requerido}")
    @Size(max = 100, message = "{message.mtrTipoFirma.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "descripcion", nullable = false, unique = true, length = 100)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public MtrTipoFirma descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [orden] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "orden", nullable = false, precision = 10)
    public Integer getOrden() {
        return orden;
    }

    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    public MtrTipoFirma orden(Integer orden) {
        setOrden(orden);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MtrTipoFirma withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MtrTipoFirma && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getCodigoTipoFirma());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warning("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this MtrTipoFirma instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("codigoTipoFirma", getCodigoTipoFirma()) //
                .add("descripcion", getDescripcion()) //
                .add("orden", getOrden()) //
                .toString();
    }
}
