/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(MtrVendedor.class)
public abstract class MtrVendedor_ {

    // Raw attributes
    public static volatile SingularAttribute<MtrVendedor, Integer> id;
    public static volatile SingularAttribute<MtrVendedor, String> nroDocumento;
    public static volatile SingularAttribute<MtrVendedor, String> telefono;
    public static volatile SingularAttribute<MtrVendedor, String> nombre;
    public static volatile SingularAttribute<MtrVendedor, String> apellidoParterno;
    public static volatile SingularAttribute<MtrVendedor, String> apellidoMaterno;
    public static volatile SingularAttribute<MtrVendedor, String> estado;

    // Many to one
    public static volatile SingularAttribute<MtrVendedor, MtrProveedor> mtrProveedor;
}
