/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Participante.class)
public abstract class Participante_ {

    // Raw attributes
    public static volatile SingularAttribute<Participante, Integer> id;
    public static volatile SingularAttribute<Participante, String> nombre;
    public static volatile SingularAttribute<Participante, String> apellido;
    public static volatile SingularAttribute<Participante, String> sexo;
    public static volatile SingularAttribute<Participante, Integer> edad;
    public static volatile SingularAttribute<Participante, String> profesion;
    public static volatile SingularAttribute<Participante, String> rol;
}
