/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityrequirenewDTO.java.e.vm
 */
package com.incloud.hcp.service.requireNew;

import com.incloud.hcp.domain.CerNotaPedidoAdjunto;
import com.incloud.hcp.service._framework.JPACustomRequiredNewService;

/**
 * Simple Interface for CerNotaPedidoAdjunto para Carga Masiva.
 */
public interface CerNotaPedidoAdjuntoRequireNewService extends JPACustomRequiredNewService<CerNotaPedidoAdjunto> {

}
