/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.domain.AppParametria;
import com.incloud.hcp.repository.AppParametriaRepository;
import com.incloud.hcp.service.AppParametriaService;
import com.incloud.hcp.service.dto.MensajeSapDto;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * A simple DTO Facility for AppParametria.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public  class AppParametriaServiceImpl  implements AppParametriaService {
    @Autowired
    protected AppParametriaRepository appParametriaRepository;

    public AppParametria getParametroPorId(Integer id) throws Exception {
        return this.appParametriaRepository.obtenerParametriaPorId(id);
    }

    public MensajeSapDto grabarParametro() throws Exception{
        AppParametria param = new AppParametria();
        param.setDescription("prueba02");
        param.setLabel("label02");
        param.setStatus("1");
        param.setModulo("modulo 02");
        param.setValue1("002");
         this.appParametriaRepository.save(param);

        MensajeSapDto dto = new MensajeSapDto();
        dto.setType("E");
        dto.setMensaje("Se grabó correctamente");

        return dto;
    }
}
