/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.common.enums.AppParametriaLabelEnum;
import com.incloud.hcp.common.enums.AppParametriaModuloEnum;
import com.incloud.hcp.common.excel.ExcelDefault;
import com.incloud.hcp.common.graph.GraphBarChart;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.common.graph.GraphDataset;
import com.incloud.hcp.common.graph.GraphPieChart;
import com.incloud.hcp.domain.*;
import com.incloud.hcp.domain.response.FacImputacionResponse;
import com.incloud.hcp.exception.ServiceException;
import com.incloud.hcp.repository.delta.*;
import com.incloud.hcp.service.FacImputacionService;
import com.incloud.hcp.service._framework.bean.BeanCargaMasivoDTO;
import com.incloud.hcp.service._framework.bean.BeanListaMasivoDTO;
import com.incloud.hcp.service._framework.impl.JPACustomServiceImpl;
import com.incloud.hcp.service.delta.FacFacturaDeltaService;
import com.incloud.hcp.service.delta.MtrCuentaImputacionDeltaService;
import com.incloud.hcp.service.delta.MtrCuentaMayorDeltaService;
import com.incloud.hcp.service.requireNew.FacImputacionRequireNewService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.utils.Constants;
import com.incloud.hcp.utils.PredicateUtils;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A simple DTO Facility for FacImputacion.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class FacImputacionServiceImpl extends JPACustomServiceImpl<FacImputacionResponse, FacImputacion, Integer> implements FacImputacionService {

    protected final String NAME_SHEET = "FacImputacion";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/FacImputacionExcel.xml";
    private final Integer REGISTROS_COLOR = 10;

    @Autowired
    protected AppParametriaDeltaRepository appParametriaDeltaRepository;

    @Autowired
    protected FacImputacionDeltaRepository facImputacionDeltaRepository;

    @Autowired
    protected FacImputacionRequireNewService facImputacionRequireNewService;

    @Autowired
    protected MtrCuentaMayorDeltaService mtrCuentaMayorDeltaService;

    @Autowired
    protected MtrCuentaMayorDeltaRepository mtrCuentaMayorDeltaRepository;

    @Autowired
    protected MtrCuentaImputacionDeltaService mtrCuentaImputacionDeltaService;

    @Autowired
    protected MtrCuentaImputacionDeltaRepository mtrCuentaImputacionDeltaRepository;

    @Autowired
    protected FacFacturaDeltaService facFacturaDeltaService;

    @Autowired
    protected FacFacturaDeltaRepository facFacturaDeltaRepository;

    /*****************************/
    /* Metodos de Busqueda       */
    /*****************************/

    protected final ExampleMatcher setAbstractFind(ExampleMatcher matcher) {
        matcher = ExampleMatcher.matching() //
                .withMatcher(FacImputacion_.estado.getName(), match -> match.ignoreCase().startsWith());
        return matcher;
    }

    protected abstract Sort setFindAll(Sort sort);

    protected abstract Sort setFind(FacImputacion req, ExampleMatcher matcher, Example<FacImputacion> example, Sort sort);

    protected abstract void setFindPaginated(PageRequestByExample<FacImputacion> req, ExampleMatcher matcher, Example<FacImputacion> example);

    protected final FacImputacion setObtenerBeanResponse(FacImputacionResponse bean) {
        return bean.getBean();
    }

    protected final Class<FacImputacion> setObtenerClassBean() {
        return FacImputacion.class;
    }

    protected List<Predicate> setAbstractPredicate(FacImputacionResponse bean, CriteriaBuilder cb, Root<FacImputacion> root) {
        List<Predicate> predicates = new ArrayList<>();
        FacImputacion entity = bean.getBean();
        /* Obtener condiciones */
        PredicateUtils.addPredicates(predicates, bean.getIdCondicion(), "id", entity.getId(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getValorImputacionCondicion(), "valorImputacion", entity.getValorImputacion(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getEstadoCondicion(), "estado", entity.getEstado(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getPorcentajeCondicion(), "porcentaje", entity.getPorcentaje(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getValorOtrosCargosCondicion(), "valorOtrosCargos", entity.getValorOtrosCargos(), cb, root);
        //PredicateUtils.addPredicates(predicates, bean.getMtrCuentaMayorCondicion(), "mtrCuentaMayor", entity.getMtrCuentaMayor(), cb, root);
        //PredicateUtils.addPredicates(predicates, bean.getMtrCuentaImputacionCondicion(), "mtrCuentaImputacion", entity.getMtrCuentaImputacion(), cb, root);
        //PredicateUtils.addPredicates(predicates, bean.getFacFacturaCondicion(), "facFactura", entity.getFacFactura(), cb, root);
        /* Obtener valores de Lista */
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "id", bean.getIdList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "valorImputacion", bean.getValorImputacionList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "estado", bean.getEstadoList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "porcentaje", bean.getPorcentajeList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "valorOtrosCargos", bean.getValorOtrosCargosList(), cb, root);
        //PredicateUtils.addPredicatesListValorBean(predicates, "mtrCuentaMayor", bean.getMtrCuentaMayorList(), cb, root);
        //PredicateUtils.addPredicatesListValorBean(predicates, "mtrCuentaImputacion", bean.getMtrCuentaImputacionList(), cb, root);
        //PredicateUtils.addPredicatesListValorBean(predicates, "facFactura", bean.getFacFacturaList(), cb, root);
        return predicates;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected final String validacionesPrevias(FacImputacion bean) throws Exception {
        String mensaje = "";
        if (!Optional.of(bean.getValorImputacion()).isPresent()) {
            String msg = this.messageSource.getMessage("message.facImputacion.valorImputacion.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        if (!Optional.of(bean.getEstado()).isPresent()) {
            String msg = this.messageSource.getMessage("message.facImputacion.estado.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        String msg = this.setValidacionesPrevias(bean);
        if (StringUtils.isNotBlank(msg)) {
            mensaje += "* " + msg + "<br/>";
        }
        return mensaje;
    }

    protected String setValidacionesPrevias(FacImputacion bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected String validacionesPreviasCreate(FacImputacion bean) throws Exception {
        String msg = null;
        FacImputacion validar = null;
        return msg;
    }

    protected String validacionesPreviasSave(FacImputacion bean) throws Exception {
        String msg = null;
        FacImputacion validar = null;
        return msg;
    }

    protected FacImputacion completarDatosBean(FacImputacion bean) throws Exception {
        BigDecimal data = new BigDecimal(0.00);
        if (Optional.ofNullable(bean.getValorImputacion()).isPresent()) {
            bean.setValorImputacion(bean.getValorImputacion().setScale(2, BigDecimal.ROUND_HALF_UP));
        }
        if (Optional.ofNullable(bean.getPorcentaje()).isPresent()) {
            data = new BigDecimal(bean.getPorcentaje().floatValue()).setScale(2, BigDecimal.ROUND_HALF_UP);
            bean.setPorcentaje(data.doubleValue());
        }
        if (Optional.ofNullable(bean.getValorOtrosCargos()).isPresent()) {
            bean.setValorOtrosCargos(bean.getValorOtrosCargos().setScale(2, BigDecimal.ROUND_HALF_UP));
        }
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected FacImputacion setCompletarDatosBean(FacImputacion bean) throws Exception {
        return bean;
    }

    protected final FacImputacion setAbstractCreate(FacImputacion dto) throws Exception {
        FacImputacion bean = new FacImputacion();
        bean = (FacImputacion) BeanUtils.cloneBean(dto);
        return bean;
    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected FacImputacion setUploadExcel(Cell currentCell, FacImputacion facImputacion, int contador) throws Exception {
        Double valorDouble = new Double(0);
        BigDecimal valorDecimal = new BigDecimal(0);
        Boolean valorBoolean = new Boolean(true);
        String valorCadena = "";
        switch (contador) {
        case 1:
            try {
                valorDecimal = new BigDecimal(currentCell.getNumericCellValue());
                facImputacion.setValorImputacion(valorDecimal);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo valorImputacion está en formato incorrecto");
            }
            break;
        case 2:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 1) {
                    throw new ServiceException("Valor Campo estado contiene mas de 1 caracter(es)");
                }
                facImputacion.setEstado(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo estado está en formato incorrecto");
            }
            break;
        case 3:
            try {
                valorDouble = new Double(currentCell.getNumericCellValue());
                facImputacion.setPorcentaje(valorDouble);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo porcentaje está en formato incorrecto");
            }
            break;
        case 4:
            try {
                valorDecimal = new BigDecimal(currentCell.getNumericCellValue());
                facImputacion.setValorOtrosCargos(valorDecimal);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo valorOtrosCargos está en formato incorrecto");
            }
            break;
        default:
            break;
        }
        return facImputacion;
    }

    protected AppParametria setObtenerRegistroConfiguracionUploadExcel() {
        AppParametria appParametriaData = this.appParametriaDeltaRepository.getByModuloAndLabelAndStatus(AppParametriaModuloEnum.CARGA_EXCEL.getEstado(),
                AppParametriaLabelEnum.INICIO_REGISTRO_DATA.getEstado(), Constants.ESTADO_ACTIVO);
        return appParametriaData;
    }

    protected FacImputacion setInicializarBeanUpdateExcel() {
        FacImputacion bean = new FacImputacion();
        bean.setId(null);
        return bean;
    }

    protected final Integer setObtenerId(FacImputacion bean) {
        return bean.getId();
    }

    /************************/
    /* Instancia de Bean    */
    /************************/

    protected final FacImputacion createInstance() {
        FacImputacion facImputacion = new FacImputacion();
        return facImputacion;
    }

    protected final BeanCargaMasivoDTO<FacImputacion> createInstanceMasivoDTO() {
        BeanCargaMasivoDTO<FacImputacion> beanCargaMasivoDTO = new BeanCargaMasivoDTO<FacImputacion>();
        return beanCargaMasivoDTO;

    }

    protected final BeanListaMasivoDTO<BeanCargaMasivoDTO<FacImputacion>> createInstanceListaMasivoDTO() {
        BeanListaMasivoDTO<BeanCargaMasivoDTO<FacImputacion>> beanCargaMasivoDTOBeanListaMasivoDTO = new BeanListaMasivoDTO<BeanCargaMasivoDTO<FacImputacion>>();
        return beanCargaMasivoDTOBeanListaMasivoDTO;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected String devuelveNombreSheet() {
        return this.NAME_SHEET;
    }

    protected String devuelveListaHeaderExcelXML() {
        return this.CONFIG_TITLE;
    }

    protected int setAbstractDownloadExcel(FacImputacion bean, HSSFRow dataRow) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getValorImputacion(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getEstado(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getPorcentaje(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getValorOtrosCargos(), dataRow.createCell(contador));
        contador++;
        return contador;
    }

    protected int setAbstractDownloadExcelSXLSX(FacImputacion bean, Row dataRow, List<CellStyle> cellStyleList) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getValorImputacion(), dataRow.createCell(contador), "N", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getEstado(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getPorcentaje(), dataRow.createCell(contador), "N", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getValorOtrosCargos(), dataRow.createCell(contador), "N", cellStyleList);
        contador++;
        return contador;
    }

    protected String setAbstractGenerateInsertExcelSXLSX(FacImputacion bean) {
        String fechaS = "";
        String sqlInsert = "INSERT INTO fac_imputacion(";
        sqlInsert = sqlInsert + "fac_imputacion_id" + ", ";
        sqlInsert = sqlInsert + "valor_imputacion" + ", ";
        sqlInsert = sqlInsert + "estado" + ", ";
        sqlInsert = sqlInsert + "porcentaje" + ", ";
        sqlInsert = sqlInsert + "valor_otros_cargos" + ", ";
        sqlInsert = sqlInsert + "fac_factura_id" + ", ";
        sqlInsert = sqlInsert + "mtr_cuenta_imputacion_id" + ", ";
        sqlInsert = sqlInsert + "mtr_cuenta_mayor_id" + ")";
        sqlInsert = sqlInsert + " VALUES (";
        sqlInsert = sqlInsert + bean.getId() + ", ";
        sqlInsert = sqlInsert + bean.getValorImputacion() + ", ";
        if (StringUtils.isBlank(bean.getEstado())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getEstado() + "'" + ", ";
        }
        sqlInsert = sqlInsert + bean.getPorcentaje() + ", ";
        sqlInsert = sqlInsert + bean.getValorOtrosCargos() + ", ";
        sqlInsert = sqlInsert + bean.getMtrCuentaMayor().getId() + ", ";
        sqlInsert = sqlInsert + bean.getMtrCuentaImputacion().getId() + ", ";
        sqlInsert = sqlInsert + bean.getFacFactura().getId();
        sqlInsert = sqlInsert + " );";
        return sqlInsert;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    public Long countByMtrCuentaMayor(MtrCuentaMayor mtrCuentaMayor) {
        return this.facImputacionDeltaRepository.countByMtrCuentaMayor(mtrCuentaMayor);
    }

    public GraphBean graphByMtrCuentaMayor() {
        List<MtrCuentaMayor> lista = this.mtrCuentaMayorDeltaRepository.findAll();
        if (lista == null || lista.size() <= 0) {
            return null;
        }
        GraphBean graphBean = new GraphBean();

        /* Obteniendo Pie Chart */
        GraphPieChart graphPieChart = new GraphPieChart();
        GraphDataset graphDataset = new GraphDataset();
        GraphDataset[] listaGraphDataset = new GraphDataset[1];
        Long[] data = new Long[lista.size()];
        String[] labels = new String[lista.size()];
        String[] backgroundColor = new String[lista.size()];
        String[] hoverBackgroundColor = new String[lista.size()];
        String[] borderColor = new String[lista.size()];
        String[] hoverBorderColor = new String[lista.size()];
        int contador = 0;
        int contadorColor = 0;
        for (MtrCuentaMayor bean : lista) {
            Long valor = this.facImputacionDeltaRepository.countByMtrCuentaMayor(bean);
            String descripcion = this.setGraphDescripcionByMtrCuentaMayor(bean);
            data[contador] = valor;
            labels[contador] = descripcion;
            backgroundColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }
        }
        String titulo = this.setGraphPieChartTituloByMtrCuentaMayor();
        graphDataset.setLabel(titulo);
        graphDataset.setData(data);
        graphDataset.setBackgroundColor(backgroundColor);
        graphDataset.setHoverBackgroundColor(hoverBackgroundColor);
        listaGraphDataset[0] = graphDataset;
        graphPieChart.setDatasets(listaGraphDataset);
        graphPieChart.setLabels(labels);
        graphBean.setPiechart(graphPieChart);

        GraphBarChart graphBarChart = new GraphBarChart();
        GraphDataset[] listaGraphDatasetBar = new GraphDataset[lista.size()];
        String[] labelsBar = new String[1];
        labelsBar[0] = this.setGraphBarChartTituloByMtrCuentaMayor();
        contador = 0;
        contadorColor = 0;
        for (MtrCuentaMayor bean : lista) {
            Long valor = this.facImputacionDeltaRepository.countByMtrCuentaMayor(bean);
            String descripcion = this.setGraphDescripcionByMtrCuentaMayor(bean);
            GraphDataset graphDatasetBar = new GraphDataset();
            Long[] dataBar = new Long[1];

            String[] backgroundColorBar = new String[1];
            String[] hoverBackgroundColorBar = new String[1];
            String[] borderColorBar = new String[1];
            String[] hoverBorderColorBar = new String[1];

            dataBar[0] = valor;
            backgroundColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];

            graphDatasetBar.setLabel(descripcion);
            graphDatasetBar.setData(dataBar);
            graphDatasetBar.setBackgroundColor(backgroundColorBar);
            graphDatasetBar.setHoverBackgroundColor(hoverBackgroundColorBar);
            graphDatasetBar.setBorderColor(borderColorBar);
            graphDatasetBar.setHoverBorderColor(hoverBorderColorBar);
            listaGraphDatasetBar[contador] = graphDatasetBar;

            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }

        }
        graphBarChart.setDatasets(listaGraphDatasetBar);
        graphBarChart.setLabels(labelsBar);
        graphBean.setBarchart(graphBarChart);
        return graphBean;
    }

    protected String setGraphDescripcionByMtrCuentaMayor(MtrCuentaMayor mtrCuentaMayor) {
        return mtrCuentaMayor.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrCuentaMayor() {
        return "MtrCuentaMayor";
    }

    protected String setGraphBarChartTituloByMtrCuentaMayor() {
        return "MtrCuentaMayor";
    }

    public Long countByMtrCuentaImputacion(MtrCuentaImputacion mtrCuentaImputacion) {
        return this.facImputacionDeltaRepository.countByMtrCuentaImputacion(mtrCuentaImputacion);
    }

    public GraphBean graphByMtrCuentaImputacion() {
        List<MtrCuentaImputacion> lista = this.mtrCuentaImputacionDeltaRepository.findAll();
        if (lista == null || lista.size() <= 0) {
            return null;
        }
        GraphBean graphBean = new GraphBean();

        /* Obteniendo Pie Chart */
        GraphPieChart graphPieChart = new GraphPieChart();
        GraphDataset graphDataset = new GraphDataset();
        GraphDataset[] listaGraphDataset = new GraphDataset[1];
        Long[] data = new Long[lista.size()];
        String[] labels = new String[lista.size()];
        String[] backgroundColor = new String[lista.size()];
        String[] hoverBackgroundColor = new String[lista.size()];
        String[] borderColor = new String[lista.size()];
        String[] hoverBorderColor = new String[lista.size()];
        int contador = 0;
        int contadorColor = 0;
        for (MtrCuentaImputacion bean : lista) {
            Long valor = this.facImputacionDeltaRepository.countByMtrCuentaImputacion(bean);
            String descripcion = this.setGraphDescripcionByMtrCuentaImputacion(bean);
            data[contador] = valor;
            labels[contador] = descripcion;
            backgroundColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }
        }
        String titulo = this.setGraphPieChartTituloByMtrCuentaImputacion();
        graphDataset.setLabel(titulo);
        graphDataset.setData(data);
        graphDataset.setBackgroundColor(backgroundColor);
        graphDataset.setHoverBackgroundColor(hoverBackgroundColor);
        listaGraphDataset[0] = graphDataset;
        graphPieChart.setDatasets(listaGraphDataset);
        graphPieChart.setLabels(labels);
        graphBean.setPiechart(graphPieChart);

        GraphBarChart graphBarChart = new GraphBarChart();
        GraphDataset[] listaGraphDatasetBar = new GraphDataset[lista.size()];
        String[] labelsBar = new String[1];
        labelsBar[0] = this.setGraphBarChartTituloByMtrCuentaImputacion();
        contador = 0;
        contadorColor = 0;
        for (MtrCuentaImputacion bean : lista) {
            Long valor = this.facImputacionDeltaRepository.countByMtrCuentaImputacion(bean);
            String descripcion = this.setGraphDescripcionByMtrCuentaImputacion(bean);
            GraphDataset graphDatasetBar = new GraphDataset();
            Long[] dataBar = new Long[1];

            String[] backgroundColorBar = new String[1];
            String[] hoverBackgroundColorBar = new String[1];
            String[] borderColorBar = new String[1];
            String[] hoverBorderColorBar = new String[1];

            dataBar[0] = valor;
            backgroundColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];

            graphDatasetBar.setLabel(descripcion);
            graphDatasetBar.setData(dataBar);
            graphDatasetBar.setBackgroundColor(backgroundColorBar);
            graphDatasetBar.setHoverBackgroundColor(hoverBackgroundColorBar);
            graphDatasetBar.setBorderColor(borderColorBar);
            graphDatasetBar.setHoverBorderColor(hoverBorderColorBar);
            listaGraphDatasetBar[contador] = graphDatasetBar;

            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }

        }
        graphBarChart.setDatasets(listaGraphDatasetBar);
        graphBarChart.setLabels(labelsBar);
        graphBean.setBarchart(graphBarChart);
        return graphBean;
    }

    protected String setGraphDescripcionByMtrCuentaImputacion(MtrCuentaImputacion mtrCuentaImputacion) {
        return mtrCuentaImputacion.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrCuentaImputacion() {
        return "MtrCuentaImputacion";
    }

    protected String setGraphBarChartTituloByMtrCuentaImputacion() {
        return "MtrCuentaImputacion";
    }

    public Long countByFacFactura(FacFactura facFactura) {
        return this.facImputacionDeltaRepository.countByFacFactura(facFactura);
    }

    public GraphBean graphByFacFactura() {
        List<FacFactura> lista = this.facFacturaDeltaRepository.findAll();
        if (lista == null || lista.size() <= 0) {
            return null;
        }
        GraphBean graphBean = new GraphBean();

        /* Obteniendo Pie Chart */
        GraphPieChart graphPieChart = new GraphPieChart();
        GraphDataset graphDataset = new GraphDataset();
        GraphDataset[] listaGraphDataset = new GraphDataset[1];
        Long[] data = new Long[lista.size()];
        String[] labels = new String[lista.size()];
        String[] backgroundColor = new String[lista.size()];
        String[] hoverBackgroundColor = new String[lista.size()];
        String[] borderColor = new String[lista.size()];
        String[] hoverBorderColor = new String[lista.size()];
        int contador = 0;
        int contadorColor = 0;
        for (FacFactura bean : lista) {
            Long valor = this.facImputacionDeltaRepository.countByFacFactura(bean);
            String descripcion = this.setGraphDescripcionByFacFactura(bean);
            data[contador] = valor;
            labels[contador] = descripcion;
            backgroundColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }
        }
        String titulo = this.setGraphPieChartTituloByFacFactura();
        graphDataset.setLabel(titulo);
        graphDataset.setData(data);
        graphDataset.setBackgroundColor(backgroundColor);
        graphDataset.setHoverBackgroundColor(hoverBackgroundColor);
        listaGraphDataset[0] = graphDataset;
        graphPieChart.setDatasets(listaGraphDataset);
        graphPieChart.setLabels(labels);
        graphBean.setPiechart(graphPieChart);

        GraphBarChart graphBarChart = new GraphBarChart();
        GraphDataset[] listaGraphDatasetBar = new GraphDataset[lista.size()];
        String[] labelsBar = new String[1];
        labelsBar[0] = this.setGraphBarChartTituloByFacFactura();
        contador = 0;
        contadorColor = 0;
        for (FacFactura bean : lista) {
            Long valor = this.facImputacionDeltaRepository.countByFacFactura(bean);
            String descripcion = this.setGraphDescripcionByFacFactura(bean);
            GraphDataset graphDatasetBar = new GraphDataset();
            Long[] dataBar = new Long[1];

            String[] backgroundColorBar = new String[1];
            String[] hoverBackgroundColorBar = new String[1];
            String[] borderColorBar = new String[1];
            String[] hoverBorderColorBar = new String[1];

            dataBar[0] = valor;
            backgroundColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];

            graphDatasetBar.setLabel(descripcion);
            graphDatasetBar.setData(dataBar);
            graphDatasetBar.setBackgroundColor(backgroundColorBar);
            graphDatasetBar.setHoverBackgroundColor(hoverBackgroundColorBar);
            graphDatasetBar.setBorderColor(borderColorBar);
            graphDatasetBar.setHoverBorderColor(hoverBorderColorBar);
            listaGraphDatasetBar[contador] = graphDatasetBar;

            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }

        }
        graphBarChart.setDatasets(listaGraphDatasetBar);
        graphBarChart.setLabels(labelsBar);
        graphBean.setBarchart(graphBarChart);
        return graphBean;
    }

    protected String setGraphDescripcionByFacFactura(FacFactura facFactura) {
        return facFactura.getId().toString();
    }

    protected String setGraphPieChartTituloByFacFactura() {
        return "FacFactura";
    }

    protected String setGraphBarChartTituloByFacFactura() {
        return "FacFactura";
    }

}
