/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.common.enums.AppParametriaLabelEnum;
import com.incloud.hcp.common.enums.AppParametriaModuloEnum;
import com.incloud.hcp.common.excel.ExcelDefault;
import com.incloud.hcp.domain.AppParametria;
import com.incloud.hcp.domain.MtrClaseDocumento;
import com.incloud.hcp.domain.MtrClaseDocumento_;
import com.incloud.hcp.domain.response.MtrClaseDocumentoResponse;
import com.incloud.hcp.exception.ServiceException;
import com.incloud.hcp.repository.delta.AppParametriaDeltaRepository;
import com.incloud.hcp.repository.delta.MtrClaseDocumentoDeltaRepository;
import com.incloud.hcp.service.MtrClaseDocumentoService;
import com.incloud.hcp.service._framework.bean.BeanCargaMasivoDTO;
import com.incloud.hcp.service._framework.bean.BeanListaMasivoDTO;
import com.incloud.hcp.service._framework.impl.JPACustomServiceImpl;
import com.incloud.hcp.service.requireNew.MtrClaseDocumentoRequireNewService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.utils.Constants;
import com.incloud.hcp.utils.PredicateUtils;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A simple DTO Facility for MtrClaseDocumento.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class MtrClaseDocumentoServiceImpl extends JPACustomServiceImpl<MtrClaseDocumentoResponse, MtrClaseDocumento, Integer>
        implements MtrClaseDocumentoService {

    protected final String NAME_SHEET = "MtrClaseDocumento";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/MtrClaseDocumentoExcel.xml";
    private final Integer REGISTROS_COLOR = 10;

    @Autowired
    protected AppParametriaDeltaRepository appParametriaDeltaRepository;

    @Autowired
    protected MtrClaseDocumentoDeltaRepository mtrClaseDocumentoDeltaRepository;

    @Autowired
    protected MtrClaseDocumentoRequireNewService mtrClaseDocumentoRequireNewService;

    /*****************************/
    /* Metodos de Busqueda       */
    /*****************************/

    protected final ExampleMatcher setAbstractFind(ExampleMatcher matcher) {
        matcher = ExampleMatcher.matching() //
                .withMatcher(MtrClaseDocumento_.codigoSap.getName(), match -> match.ignoreCase().startsWith())
                .withMatcher(MtrClaseDocumento_.descripcion.getName(), match -> match.ignoreCase().startsWith())
                .withMatcher(MtrClaseDocumento_.estado.getName(), match -> match.ignoreCase().startsWith());
        return matcher;
    }

    protected abstract Sort setFindAll(Sort sort);

    protected abstract Sort setFind(MtrClaseDocumento req, ExampleMatcher matcher, Example<MtrClaseDocumento> example, Sort sort);

    protected abstract void setFindPaginated(PageRequestByExample<MtrClaseDocumento> req, ExampleMatcher matcher, Example<MtrClaseDocumento> example);

    protected final MtrClaseDocumento setObtenerBeanResponse(MtrClaseDocumentoResponse bean) {
        return bean.getBean();
    }

    protected final Class<MtrClaseDocumento> setObtenerClassBean() {
        return MtrClaseDocumento.class;
    }

    protected List<Predicate> setAbstractPredicate(MtrClaseDocumentoResponse bean, CriteriaBuilder cb, Root<MtrClaseDocumento> root) {
        List<Predicate> predicates = new ArrayList<>();
        MtrClaseDocumento entity = bean.getBean();
        /* Obtener condiciones */
        PredicateUtils.addPredicates(predicates, bean.getIdCondicion(), "id", entity.getId(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getCodigoSapCondicion(), "codigoSap", entity.getCodigoSap(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getDescripcionCondicion(), "descripcion", entity.getDescripcion(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getEstadoCondicion(), "estado", entity.getEstado(), cb, root);
        /* Obtener valores de Lista */
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "id", bean.getIdList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "codigoSap", bean.getCodigoSapList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "descripcion", bean.getDescripcionList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "estado", bean.getEstadoList(), cb, root);
        return predicates;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected final String validacionesPrevias(MtrClaseDocumento bean) throws Exception {
        String mensaje = "";
        if (!Optional.of(bean.getCodigoSap()).isPresent()) {
            String msg = this.messageSource.getMessage("message.mtrClaseDocumento.codigoSap.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        if (!Optional.of(bean.getDescripcion()).isPresent()) {
            String msg = this.messageSource.getMessage("message.mtrClaseDocumento.descripcion.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        if (!Optional.of(bean.getEstado()).isPresent()) {
            String msg = this.messageSource.getMessage("message.mtrClaseDocumento.estado.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        String msg = this.setValidacionesPrevias(bean);
        if (StringUtils.isNotBlank(msg)) {
            mensaje += "* " + msg + "<br/>";
        }
        return mensaje;
    }

    protected String setValidacionesPrevias(MtrClaseDocumento bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected String validacionesPreviasCreate(MtrClaseDocumento bean) throws Exception {
        String msg = null;
        MtrClaseDocumento validar = null;
        validar = this.mtrClaseDocumentoDeltaRepository.getByCodigoSap(bean.getCodigoSap());
        if (Optional.ofNullable(validar).isPresent()) {
            msg = this.messageSource.getMessage("message.mtrClaseDocumento.codigoSap.duplicado", null, LocaleContextHolder.getLocale());
            return msg;
        }
        validar = this.mtrClaseDocumentoDeltaRepository.getByDescripcion(bean.getDescripcion());
        if (Optional.ofNullable(validar).isPresent()) {
            msg = this.messageSource.getMessage("message.mtrClaseDocumento.descripcion.duplicado", null, LocaleContextHolder.getLocale());
            return msg;
        }
        return msg;
    }

    protected String validacionesPreviasSave(MtrClaseDocumento bean) throws Exception {
        String msg = null;
        MtrClaseDocumento validar = null;
        validar = this.mtrClaseDocumentoDeltaRepository.getByCodigoSap(bean.getCodigoSap());
        if (Optional.ofNullable(validar).isPresent()) {
            if (bean.getId().intValue() != validar.getId().intValue()) {
                msg = this.messageSource.getMessage("message.mtrClaseDocumento.codigoSap.duplicado", null, LocaleContextHolder.getLocale());
                return msg;
            }
        }
        validar = this.mtrClaseDocumentoDeltaRepository.getByDescripcion(bean.getDescripcion());
        if (Optional.ofNullable(validar).isPresent()) {
            if (bean.getId().intValue() != validar.getId().intValue()) {
                msg = this.messageSource.getMessage("message.mtrClaseDocumento.descripcion.duplicado", null, LocaleContextHolder.getLocale());
                return msg;
            }
        }
        return msg;
    }

    protected MtrClaseDocumento completarDatosBean(MtrClaseDocumento bean) throws Exception {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected MtrClaseDocumento setCompletarDatosBean(MtrClaseDocumento bean) throws Exception {
        return bean;
    }

    protected final MtrClaseDocumento setAbstractCreate(MtrClaseDocumento dto) throws Exception {
        MtrClaseDocumento bean = new MtrClaseDocumento();
        bean = (MtrClaseDocumento) BeanUtils.cloneBean(dto);
        return bean;
    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrClaseDocumento setUploadExcel(Cell currentCell, MtrClaseDocumento mtrClaseDocumento, int contador) throws Exception {
        Double valorDouble = new Double(0);
        BigDecimal valorDecimal = new BigDecimal(0);
        Boolean valorBoolean = new Boolean(true);
        String valorCadena = "";
        switch (contador) {
        case 1:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 3) {
                    throw new ServiceException("Valor Campo codigoSap contiene mas de 3 caracter(es)");
                }
                mtrClaseDocumento.setCodigoSap(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo codigoSap está en formato incorrecto");
            }
            break;
        case 2:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 200) {
                    throw new ServiceException("Valor Campo descripcion contiene mas de 200 caracter(es)");
                }
                mtrClaseDocumento.setDescripcion(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo descripcion está en formato incorrecto");
            }
            break;
        case 3:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 1) {
                    throw new ServiceException("Valor Campo estado contiene mas de 1 caracter(es)");
                }
                mtrClaseDocumento.setEstado(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo estado está en formato incorrecto");
            }
            break;
        default:
            break;
        }
        return mtrClaseDocumento;
    }

    protected AppParametria setObtenerRegistroConfiguracionUploadExcel() {
        AppParametria appParametriaData = this.appParametriaDeltaRepository.getByModuloAndLabelAndStatus(AppParametriaModuloEnum.CARGA_EXCEL.getEstado(),
                AppParametriaLabelEnum.INICIO_REGISTRO_DATA.getEstado(), Constants.ESTADO_ACTIVO);
        return appParametriaData;
    }

    protected MtrClaseDocumento setInicializarBeanUpdateExcel() {
        MtrClaseDocumento bean = new MtrClaseDocumento();
        bean.setId(null);
        return bean;
    }

    protected final Integer setObtenerId(MtrClaseDocumento bean) {
        return bean.getId();
    }

    /************************/
    /* Instancia de Bean    */
    /************************/

    protected final MtrClaseDocumento createInstance() {
        MtrClaseDocumento mtrClaseDocumento = new MtrClaseDocumento();
        return mtrClaseDocumento;
    }

    protected final BeanCargaMasivoDTO<MtrClaseDocumento> createInstanceMasivoDTO() {
        BeanCargaMasivoDTO<MtrClaseDocumento> beanCargaMasivoDTO = new BeanCargaMasivoDTO<MtrClaseDocumento>();
        return beanCargaMasivoDTO;

    }

    protected final BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrClaseDocumento>> createInstanceListaMasivoDTO() {
        BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrClaseDocumento>> beanCargaMasivoDTOBeanListaMasivoDTO = new BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrClaseDocumento>>();
        return beanCargaMasivoDTOBeanListaMasivoDTO;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected String devuelveNombreSheet() {
        return this.NAME_SHEET;
    }

    protected String devuelveListaHeaderExcelXML() {
        return this.CONFIG_TITLE;
    }

    protected int setAbstractDownloadExcel(MtrClaseDocumento bean, HSSFRow dataRow) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getCodigoSap(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getDescripcion(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getEstado(), dataRow.createCell(contador));
        contador++;
        return contador;
    }

    protected int setAbstractDownloadExcelSXLSX(MtrClaseDocumento bean, Row dataRow, List<CellStyle> cellStyleList) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getCodigoSap(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getDescripcion(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getEstado(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        return contador;
    }

    protected String setAbstractGenerateInsertExcelSXLSX(MtrClaseDocumento bean) {
        String fechaS = "";
        String sqlInsert = "INSERT INTO mtr_clase_documento(";
        sqlInsert = sqlInsert + "mtr_clase_documento_id" + ", ";
        sqlInsert = sqlInsert + "codigo_sap" + ", ";
        sqlInsert = sqlInsert + "descripcion" + ", ";
        sqlInsert = sqlInsert + "estado" + ")";
        sqlInsert = sqlInsert + " VALUES (";
        sqlInsert = sqlInsert + bean.getId() + ", ";
        if (StringUtils.isBlank(bean.getCodigoSap())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getCodigoSap() + "'" + ", ";
        }
        if (StringUtils.isBlank(bean.getDescripcion())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getDescripcion() + "'" + ", ";
        }
        if (StringUtils.isBlank(bean.getEstado())) {
            sqlInsert = sqlInsert + "null";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getEstado() + "'";
        }
        sqlInsert = sqlInsert + " );";
        return sqlInsert;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
